/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function b(b,c,d){a:{for(var e=r[b],f=0;f<e.length;++f){var g=e[f];if(0<=d.indexOf(g))for(;;c=c.parentNode){var h=a.Components.Tf(c,g);if(h){d=h;break a}}}d=null}return d?d("option","chroming"):a.Ee.Yk(b).chroming}function d(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?f(d).find(c):f(c,a.ownerDocument).filter(function(){return!this.form})):d=(b?b.filter(a):
f(a)).filter(":oj-button");return d}function c(a,b){a.removeClass(n).addClass(p[b])}a.ya("oj.ojButton",f.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{chroming:"full",disabled:!1,display:"all",label:null,icons:{start:null,end:null},menu:null},ae:function(a,b){this._super(a,b);this.Oga();"disabled"in b||this.option("disabled",!!this.element.prop("disabled"),{_context:{Wa:!0}});"label"in b||(this.Mpa=!0,this.option("label","inputPush"===this.type?this.Bd.val():this.Bd.html(),
{_context:{Wa:!0}}));!this.options.menu||b.icons&&void 0!==b.icons.end||this.option("icons.end","oj-component-icon oj-button-menu-dropdown-icon",{_context:{Hc:!0,Wa:!0}})},_ComponentCreate:function(){function a(){b.FK=Date.now();b.wb.removeClass(l);b.wb.removeClass("oj-hover");b.Nh()}this._super();this.element.closest("form").unbind("reset"+h).bind("reset"+h,function(){var a=f(this);setTimeout(function(){a.find(":oj-button").each(function(){f(this).data("oj-ojButton").GA(!1)}).length||a.unbind("reset"+
h)},1)});this.gz=this.eventNamespace+"menu";this.Pga();this.aO=!!this.wb.attr("title");var b=this,d=this.jx,l=d?"":"oj-active";this.wb.addClass(k);c(this.wb,this.options.chroming);this.document.bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a);this.Bd.bind("touchstart"+this.eventNamespace,function(){b.be()||(f(this).addClass(l),b.Nh())}).bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a).bind("mouseenter"+this.eventNamespace,function(){b.be()||b.Mx()||
(this===e&&b.wb.addClass("oj-active"),b.wb.addClass("oj-hover").removeClass("oj-default oj-focus-only"))}).bind("mouseleave"+this.eventNamespace,function(){b.wb.removeClass("oj-hover");b.be()||(b.wb.removeClass(l),b.Nh())}).bind("click"+this.eventNamespace,function(a){b.be()&&(a.preventDefault(),a.stopImmediatePropagation())});this.element.bind("focus"+this.eventNamespace,function(){b.wb.addClass("oj-focus");b.Nh()}).bind("blur"+this.eventNamespace,function(){b.wb.removeClass("oj-focus");b.Nh()});
d&&(this.element.bind("change"+this.eventNamespace,function(a){b.GA(!0);var c=f(this).closest(":oj-buttonset").data("oj-ojButtonset"),d=c&&c.YV(c.Fd);c&&void 0!==d&&c.option("checked",d,{_context:{Hc:!0,originalEvent:a,Wa:!0}})}),this.Bd.bind("mousedown"+this.eventNamespace,function(){b.be()||(g=this,b.document.one("mouseup",function(){g=null}))}).bind("mouseup"+this.eventNamespace,function(){b.be()||this!==g||b.element.focus()}));"checkbox"===this.type?(this.Bd.bind("click"+this.eventNamespace,function(){if(b.be())return!1}),
this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode===f.ui.keyCode.ENTER&&(b.be()||b.element.click())})):"radio"===this.type?(this.Bd.bind("click"+this.eventNamespace,function(){if(b.be())return!1}),this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode!==f.ui.keyCode.ENTER||b.element[0].checked||b.be()||(b.element[0].checked=!0,b.element.change(),b.element.click())})):(this.Bd.bind("mousedown"+this.eventNamespace,function(a){if(b.be())return!1;1!==a.which||b.Mx()||(f(this).addClass("oj-active").removeClass("oj-default oj-focus-only"),
e=this,b.document.one("mouseup",function(){e=null}))}).bind("mouseup"+this.eventNamespace,function(){if(b.be())return!1;f(this).removeClass("oj-active");b.Nh()}).bind("keydown"+this.eventNamespace,function(a){if(b.be())return!1;var c=a.keyCode===f.ui.keyCode.SPACE,d="anchor"===b.type;d&&c&&a.preventDefault();(c&&!d||a.keyCode===f.ui.keyCode.ENTER)&&f(this).addClass("oj-active").removeClass("oj-default oj-focus-only")}).bind("keyup"+this.eventNamespace+" blur"+this.eventNamespace,function(){f(this).removeClass("oj-active");
b.Nh()}),"anchor"===this.type&&(d=this.Bd.attr("tabindex"),("undefined"===d||null===d||isNaN(d))&&this.Bd.attr("tabindex","0")));this.OM();this.bga();this.E0();this.Nh()},Mx:function(){return 500>Date.now()-this.FK},uf:function(a,b,c){this.wf(b,c,{position:{of:"keyboard"===c?this.wb:b}})},Oga:function(){if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox",this.jx=!0;else if(this.element.is("input[type\x3dradio]"))this.type="radio",this.jx=!0;else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type=
"inputPush";else if(this.element.is("button"))this.type="button";else if(this.element.is("a"))this.type="anchor";else throw Error("JET Button not supported on this element type");if(this.jx){var a="label[for\x3d'"+this.element.attr("id")+"']";this.Bd=this.element.siblings().filter(a)}else this.Bd=this.element},Pga:function(){this.jx?(this.Bd.addClass("oj-button-label"),this.element.addClass("oj-button-input oj-helper-hidden-accessible").add(this.Bd).wrapAll("\x3cspan\x3e\x3c/span\x3e"),this.wb=this.element.parent(),
this.wb.addClass("oj-button-toggle"),this.element[0].checked&&this.wb.addClass("oj-selected").removeClass("oj-default oj-focus-only")):this.wb=this.element},widget:function(){return this.wb},_destroy:function(){this.A_();this.document.off(this.eventNamespace);this.element.removeClass("oj-helper-hidden-accessible").removeUniqueId();var b=this.jx;b||this.wb.removeClass(k+" "+l+" "+m+" "+n);this.Bd.html(this.Bd.find(".oj-button-text").html());b?(this.Bd.removeClass("oj-button-label"),a.v.unwrap(this.element)):
this.aO||this.wb.removeAttr("title");g===this.Bd[0]&&(g=null)},oi:function(){this._super();this.Nh()},Wv:function(a){this._super(a);this.OM()},OM:function(){var a=this.be();this.wb.toggleClass("oj-disabled",a);this.wb.toggleClass("oj-enabled",!a);"anchor"!==this.type?(this.element.prop("disabled",a),this.wb.removeAttr("aria-disabled")):this.wb.attr("aria-disabled",a);a?(this.widget().removeClass("oj-active oj-default oj-focus-only oj-hover oj-focus"),e=null,this.qI()):this.Nh()},_setOption:function(a,
b,d){this._super(a,b,d);switch(a){case "chroming":c(this.wb,b);break;case "disabled":this.OM();break;case "label":this.tla();break;case "display":"inputPush"!==this.type&&this.bD();break;case "icons":this.qla(!0);break;case "menu":this.E0()}},refresh:function(){this._super();this.lT&&!f(this).closest(":oj-buttonset").length&&this.Wv(!1);c(this.wb,this.options.chroming)},GA:function(a){"radio"===this.type?(a?d(this.element[0]):this.element).each(function(){var a=f(this).data("oj-ojButton");this.checked?
a.wb.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(a.wb.removeClass("oj-selected"),a.Nh())}):"checkbox"===this.type&&(this.element[0].checked?this.wb.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(this.wb.removeClass("oj-selected"),this.Nh()))},bga:function(){if("inputPush"===this.type)this.p0();else{var a=this.sla(),b=this.cD(!0),c=this.cD(!1);this.bD(a,b,c)}},sla:function(){var a=this.Bd,b=f("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",this.document[0]);
this.Mpa?b.append(a.contents()):(a.empty(),b.text(this.options.label));a.append(b);return b},tla:function(){if("inputPush"===this.type)this.p0();else{var a=this.Bd.find(".oj-button-text");a.text(this.options.label);this.bD(a)}},p0:function(){this.options.label&&this.element.val(this.options.label)},qla:function(){if("inputPush"!==this.type){var a=this.cD(!0),b=this.cD(!1);this.bD(void 0,a,b)}},cD:function(a){if(a){var b=".oj-button-icon.oj-start";a="oj-button-icon oj-start";var c=this.options.icons.start,
d="_lastStartIcon",e="prependTo"}else b=".oj-button-icon.oj-end",a="oj-button-icon oj-end",c=this.options.icons.end,d="_lastEndIcon",e="appendTo";b=this.Bd.find(b);c?(b.length?b.removeClass(this[d]):b=f("\x3cspan\x3e\x3c/span\x3e").addClass(a)[e](this.Bd),b.addClass(c)):b.remove();this[d]=c;return!!c},bD:function(a,b,c){void 0===a&&(a=this.Bd.find(".oj-button-text"));void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.options.icons.end);var d=b&&c;c=b||c;var e="icons"===this.options.display;
c&&e?(a.addClass("oj-helper-hidden-accessible"),this.aO||(a=a.text(),this.wb.attr("title",f.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.aO||this.wb.removeAttr("title"));b=c?e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.wb.removeClass(m).addClass(b)},E0:function(){if(this.options.menu&&this.element.is("input"))throw Error("Menu Button functionality is not supported on input elements.");
this.A_();if(this.options.menu){var a=this;this.element.attr("aria-haspopup",!0).on("keydown"+this.gz,function(b){if(b.which===f.ui.keyCode.DOWN)a.J0(b,"firstItem"),b.preventDefault();else if(b.which===f.ui.keyCode.ESCAPE){var c=a.Saa(a.wb);a.qI(b);return c}return!0}).on("click"+this.gz,function(b){var c=a.lJ();c.yA||a.J0(b,"firstItem");c.yA=!1;b.preventDefault();return!0})}},Saa:function(a){return!a.hasClass("oj-selected")},A_:function(){this.element.removeAttr("aria-haspopup").off(this.gz);this.qI();
this.pa&&this.pa.widget().off(this.gz);this.pa=void 0},lJ:function(){if(!this.pa){this.pa=f(this.options.menu).data("oj-ojMenu");if(!this.pa)throw Error('JET Button: "menu" option specified, but does not reference a valid JET Menu.');var a=this;this.pa.widget().on("ojclose"+this.gz,function(b){a.nia(b)})}return this.pa},J0:function(a,b){if(!this.be()){var c=this.lJ(),d=c.widget();c.open(a,{launcher:this.element,initialFocus:b});this.jZ=!0;d.attr("aria-label")||d.attr("aria-labelledby")||(this.element.uniqueId(),
this.f0=!0,d.attr("aria-labelledby",this.element.attr("id")));this.wb.addClass("oj-selected").removeClass("oj-default oj-focus-only")}},qI:function(a){this.jZ&&(this.pa.WG(a,!0),this.pa.Sp(a))},nia:function(){this.f0&&(this.lJ().widget().removeAttr("aria-labelledby"),this.f0=!1);this.wb.removeClass("oj-selected");this.Nh();this.jZ=!1},Nh:function(){var a,b;this.wb.is(".oj-hover, .oj-active, .oj-selected, .oj-disabled")?b=a=!1:(b=this.wb.is(".oj-focus"),a=!b);this.wb.toggleClass("oj-default",a);this.wb.toggleClass("oj-focus-only",
b)}});a.ya("oj.ojButtonset",f.oj.baseComponent,{SY:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",options:{checked:null,chroming:"full",focusManagement:"oneTabstop"},Yx:function(a,b){var c=f.type(a),d;if("null"===c||"array"===c)d=b.filter("input[type\x3dcheckbox]").length===b.length;if(d&&"null"===c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);if("string"===c||"null"===c)(c=((c=
b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c=c||null===a;else if("array"===c){var e;(c=d&&a.concat().sort().every(function(a){var c=a!==e&&b.filter("[value\x3d"+a+"]").length;e=a;return c}))&&b.each(function(){this.checked=-1<a.indexOf(this.value)})}else c=!1;if(!c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);},YV:function(a){var b=
void 0,c=null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},Fv:function(a,b,c){return"checked"===a?b===c?!0:"array"===f.type(b)&&
"array"===f.type(c)&&!f(b).not(c).length&&!f(c).not(b).length:this._superApply(arguments)},ae:function(a,b){this._super(a,b);this.Fd=this.element.find(this.SY);if(!("checked"in b)){this.cO=!0;var c=this.YV(this.Fd);"array"===f.type(c)&&(this.options.checked=[]);void 0!==c&&this.option("checked",c,{_context:{Wa:!0}})}},_ComponentCreate:function(){this._super();this.element.attr(a.Components.xn,this.widgetName).addClass("oj-buttonset oj-component");this.A0(this.options.focusManagement);this.Ba(!0)},
uf:function(a,b,c){a=this.element.find(":oj-button[tabindex\x3d0]");this.wf(b,c,{launcher:a,position:{of:"keyboard"===c?a.ojButton("widget"):b}})},uo:function(a){a=!!a;this.Fd.each(function(){f(this).data("oj-ojButton").Wv(a)})},A0:function(a){"oneTabstop"===a?this.element.attr("role","toolbar"):this.element.removeAttr("role")},_setOption:function(a,b,d){this._superApply(arguments);"disabled"===a?this.uo(b):"checked"===a?(this.Yx(b,this.Fd),this.Fd.each(function(){f(this).data("oj-ojButton").GA(!1)})):
"focusManagement"===a?this.A0(b):"chroming"===a&&(c(this.element,b),this.Fd.ojButton("refresh"))},refresh:function(){this._super();this.Ba(!1)},Ba:function(a){var b=this;this.Uf="rtl"===this.dc();c(this.element,this.options.chroming);a?this.cO||this.Yx(this.options.checked,this.Fd):this.Fd=this.element.find(this.SY);this.element.toggleClass("oj-buttonset-multi",1<this.Fd.length);this.Fd.filter(":oj-button").ojButton("refresh").each(function(){f(this).data("oj-ojButton").GA(!1)}).end().not(":oj-button").ojButton().end().map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").filter(":first").addClass("oj-buttonset-first").end().filter(":last").addClass("oj-buttonset-last").end().end();
this.uo(this.options.disabled);"oneTabstop"===this.options.focusManagement&&(this.Fd.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.xq(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).data("oj-ojButton").be()||b.Tq(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Tq(f(this))}),this.rl=this.Fd.filter(function(){return!f(this).data("oj-ojButton").be()}),this.qK(a))},
qK:function(a){var b=f(this.Hq);this.Hq=void 0;this.Fd.attr("tabindex","-1");a=a||!b.is(this.rl)?this.rl.first():b;this.Tq(a)},JK:function(a){var b=this.rl;return a.map(function(a,c){if("radio"!=c.type||c.checked||""==c.name)return c;var e=d(c,b).filter(":checked");return e.length?e[0]:c})},Tq:function(a){a=this.JK(a);var b=a[0],c=this.Hq;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Hq=b)},xq:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();
var c=this.rl,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==f.ui.keyCode.RIGHT^this.Uf?1:-1)+d)%d).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component "+n).removeAttr(a.Components.xn).removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.Fd.attr("tabindex","0");this.Fd.map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").end().ojButton("destroy")}});
var e,g,h=".ojButton",k="oj-button oj-component oj-enabled oj-default",l="oj-hover oj-active oj-selected",m="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only",n="oj-button-full-chrome oj-button-half-chrome oj-button-outlined-chrome",p={full:"oj-button-full-chrome",half:"oj-button-half-chrome",outlined:"oj-button-outlined-chrome"},r={button:["ojButtonset","ojToolbar"],buttonset:["ojToolbar"]};a.Components.Tm({ojButton:{chroming:a.Components.nh(function(a){return b("button",
a.element,a.containers)})},ojButtonset:{chroming:a.Components.nh(function(a){return b("buttonset",a.element,a.containers)})}})})()});