/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","ojs/ojknockout"],function(a,f){function b(a,b){var c=null,d=a[b];if(null!=d){c=Object.keys(d)[0];d=d[c];if(null==c)throw"Invalid component descriptor key";switch(c){case "inline":c=Promise.resolve(d);break;case "promise":c=d;break;default:throw"Invalid descriptor key "+c+" for the resopurce type: "+b;}}return c}function d(b,c,d){if(null!=b&&(c=a.Xh.hc[c],null!=c&&b&&(c=b[c],"function"===typeof c)))return f.ignoreDependencies(c,b,d)}function c(a,b,c,d){k(c,"properties",
function(c,e){g(a,b,c,e,d)})}function e(a,b,c){k(b,"methods",function(d){var e=b.methods[d].internalName;a[d]=e?c[e].bind(c):c[d].bind(c)})}function g(a,b,c,d,e){function g(b){var d=k.peek();d!==b&&(k(b),e.Hpa()||(b=new CustomEvent(c+"-changed",{detail:{value:b,previousValue:d}}),a.dispatchEvent(b)))}var k=f.observable();h(b,c,function(){return k()},g);h(a,c,function(){return k.peek()},function(a){if(d.readOnly)throw"Read-only property "+c+" cannot be set";g(a)})}function h(a,b,c,d){Object.defineProperty(a,
b,{configurable:!0,enumerable:!0,get:c,set:d})}function k(a,b,c){if(a){var d=a[b]||{};Object.keys(d).forEach(function(a){c(a,d[a])})}}function l(a,b){["methods","properties"].forEach(function(c){k(b,c,function(b){delete a[b]})})}function m(a){var b={};a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if((1===d.nodeType||3===d.nodeType)&&(3!==d.nodeType||d.nodeValue.trim())){var e=d.__oj_slots;(e=null!=e?e:d.getAttribute&&d.getAttribute("slot"))||(e="");b[e]||(b[e]=[]);b[e].push(d)}}return b}function n(a,
b){var c,d=a.childNodes;if(d){c=document.createElement("div");c.setAttribute("data-bind","_ojNodeStorage_");c.style.display="none";b.push(c);for(var e=[],f=0;f<d.length;f++){var g=d[f];1!==g.nodeType&&3!==g.nodeType||e.push(g)}e.forEach(function(a){c.appendChild(a)})}return c}function p(b,c){function d(a,b,c){h(c,b,a)||a.readOnly||(a=e(c,a.type),n(b,a))}function e(a,b){switch(b.toLowerCase()){case "boolean":return Boolean(a);case "number":return Number(a);case "string":return a;default:return JSON.parse(a)}}
function g(a){return a.toLowerCase().replace(/-(.)/g,function(a,b){return b.toUpperCase()})}function h(d,e,g){d=a.Vr.h3(d);delete z[e];var m=p[e];m&&(m.dispose(),delete p[e]);if(m=s[e])b.removeEventListener(e+P,m),delete s[e];var v,m=g.readOnly;m||(v=function(){var a=r[e];a&&(a.dispose(),delete r[e])},v());var x=d.expr;if(x){var u=a.ia.wA(x);m||f.ignoreDependencies(function(){p[e]=f.computed(function(){v();if(!z[e]){var a=u(c);f.isObservable(a)?r[e]=k(e,a):n(e,a)}})});s[e]=l(e,x,u,g.writeback&&!d.noa);
return!0}return!1}function k(a,b){f.ignoreDependencies(function(){n(a,f.utils.unwrapObservable(b))});return b.subscribe(function(b){z[a]||n(a,b)})}function l(d,e,g,h){function k(b){var q=!1;A||(h&&f.ignoreDependencies(function(){var d=b.detail.value,h=g(c);f.isWriteableObservable(h)?(q=!0,h(d)):(h=a.Vr.t3(e),null!=h&&(a.ia.wA(h)(c)(d),q=!0))}),q||(z[d]=!0))}b.addEventListener(d+P,k);return k}function m(a){return a.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()})}function n(a,c){A=!0;try{b[a]=
c}finally{A=!1}}this.Wj=function(a){var c=a.properties;if(c){B.setAttribute=b.setAttribute;B.removeAttribute=b.removeAttribute;b.setAttribute=function(a,b){e(a,b,B.setAttribute)};b.removeAttribute=function(a){e(a,null,B.removeAttribute)};var e=function(a,e,f){a=a.toLowerCase();var h=b.getAttribute(a);f.apply(b,arguments);var k=b.getAttribute(a),l=g(a);b.hasOwnProperty(l)&&k!==h&&d(c[l],l,k)};a=Object.keys(c);L=!0;try{a.forEach(function(a){var e=m(a),f=c[a];b.hasAttribute(e)?(e=b.getAttribute(e),d(f,
a,e)):f.readOnly||(b[a]=f.value)})}finally{L=!1}}return this};this.Hpa=function(){return L};this.Zqa=function(a){var b;[r,p].forEach(function(a){b=Object.keys(a);for(a=0;a<b.length;a++)p[b[a]].dispose()});r={};p={};b=Object.keys(B);var c;for(c=0;c<b.length;c++){var d=b[c];a[d]=B[d]}B={};b=Object.keys(s);for(c=0;c<b.length;c++)d=b[c],a.removeEventListener(d+P,s[d]);s={}};var p={},r={},s={},B={},z={},L,A,P="-changed"}(function(){a.VS.N1({nodeHasBindings:function(b,c){return c||1===b.nodeType&&a.Xh.VG(b.nodeName.toLowerCase())},
getBindingAccessors:function(b,c,d){if(1===b.nodeType&&(b=b.nodeName.toLowerCase(),a.Xh.VG(b))){d=d||{};if(d.ojComposite)throw"Cannot use ojComposite binding on a custom element whose name is already registered for a composite binding";var e={name:b};d.ojComposite=function(){return e}}return d},preprocessNode:function(b,c){var d;if(1===b.nodeType&&"oj-slot"===b.nodeName.toLowerCase()){d=["name","slot","index"];for(var e="ko _ojSlot_:{",f=[],g=0;g<d.length;g++){var h=d[g],k;k=b.getAttribute(h);if(null!=
k){var l=a.Vr.h3(k).expr;null==l&&(l="'"+k+"'");k=l}else k=null;k&&f.push(h+":"+k)}e+=f.join(",");g=document.createComment(e+"}");e=document.createComment("/ko");d=[g];f=b.parentNode;for(f.insertBefore(g,b);0<b.childNodes.length;)g=b.childNodes[0],f.insertBefore(g,b),d.push(g);d.push(e);f.replaceChild(e,b)}return d?d:c}})})();a.Xh={};a.Xh.hc={initializeMethod:"initialize",activatedMethod:"activated",attachedMethod:"attached",bindingsAppliedMethod:"bindingsApplied",disposeMethod:"dispose"};o_("Composite.defaults",
a.Xh.hc,a);a.Xh.register=function(b,c){a.Xh.q_[b]=c};o_("Composite.register",a.Xh.register,a);a.Xh.VG=function(b){return a.Xh.q_[b]};a.Xh.q_={};f.bindingHandlers.ojComposite={init:function(){return{controlsDescendantBindings:!0}},update:function(g,h,k,x,u){function w(a){H&&(H.Zqa(g),H=null);G=a;d(J,"disposeMethod",[g]);J=null;E&&l(g,E);z&&(g.removeChild(z),z=null);E=null;B={}}function y(a){return function(b){if(G||b!=F)throw C;return a.apply(this,Array.prototype.slice.call(arguments,1))}.bind(null,
F)}var C=Error(),J,H,F=-1,G=!1,E,B={},z,L=f.utils.unwrapObservable;f.ignoreDependencies(function(){f.computed(function(){F++;g.dispatchEvent(new CustomEvent("pending",{bubbles:!0}));w(!1);var k=L(h())||{},k=L(k.name),l=a.Xh.VG(k);if(!l)throw"Composite is missing a descriptor";var v=b(l,"metadata"),k=null;v&&(k=v.then(y(function(b){b?(E=b,H=new p(g,u),c(g,B,b,H),H.Wj(b)):a.q.fta("ojComposite is being loaded without metadata. No element properties will be set up");return B})));var x,v=new Promise(function(a){x=
a}),I=s+r++,D={element:g,props:k,slotNodeCounts:v,unique:I},v=null,N=b(l,"viewModel");N&&(v=N.then(y(function(a){return a="function"===typeof a?new a(D):d(a,"initializeMethod",[D])||a})));N=null;v&&(N=v.then(y(function(a){return d(a,"activatedMethod",[D])})));var O=b(l,"view");O&&(O=O.then(y(function(a){if("string"===typeof a)a=f.utils.parseHtmlFragment(a);else if(window.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType)a=f.utils.arrayPushAll([],a.childNodes);else if(Array.isArray(a))a=
f.utils.arrayPushAll([],a);else throw"The View ("+a+") has an unsupported type";return a})));(l=b(l,"css"))&&(l=l.then(y(function(a){var b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));document.head.appendChild(b)})));f.applyBindingsToDescendants(u,g);Promise.all([O,v,k,l,N]).then(function(a,b){if(!G&&a==F){var c=b[0];if(!c)throw"ojComposite is missing a View";var h=m(g),k={},l;for(l in h)k[l]=h[l].length;x(k);z=n(g,
c);f.virtualElements.setDomNodeChildren(g,c);J=b[1];d(J,"attachedMethod",[D]);c=u.createChildContext(J,void 0,function(a){a.__oj_slots=h;a.__oj_nodestorage=z;a.$slotNodeCounts=k;a.$props=B;a.$unique=I});E&&J&&e(g,E,J);f.applyBindingsToDescendants(c,g);d(J,"bindingsAppliedMethod",[D]);g.dispatchEvent(new CustomEvent("ready",{bubbles:!0}))}}.bind(null,F),function(b,c){c!==C&&null!=c&&a.q.error(c)}.bind(null,F))},null,{disposeWhenNodeIsRemoved:g})});f.utils.domNodeDisposal.addDisposeCallback(g,w.bind(null,
!0,u))}};var r=0,s="_ojcomposite";f.bindingHandlers._ojNodeStorage_={init:function(){return{controlsDescendantBindings:!0}}};f.bindingHandlers._ojSlot_={init:function(a,b,c,d,e){f.utils.domNodeDisposal.addDisposeCallback(a,function(b){if(b=b.__oj_nodestorage)for(var c;c=f.virtualElements.firstChild(a);)null!=c.__oj_slots&&b.appendChild(c)}.bind(null,e));d=e.__oj_slots;b=b();c=f.utils.unwrapObservable;e=c(b.name)||"";var g=c(b.index);if(d=null!=g?[d[e][g]]:d[e]){for(e=0;e<d.length;e++)d[e].__oj_slots=
c(b.slot)||"";f.virtualElements.setDomNodeChildren(a,d);return{controlsDescendantBindings:!0}}}};f.virtualElements.allowedBindings._ojSlot_=!0});