/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","jqueryui-amd/core","jqueryui-amd/widget","ojs/ojmessaging"],function(a,f){function b(a,b){function c(){var a=f(this),d=a.data(k);if(null!=d)for(var e=0;e<d.length;e++){var g=a.data("oj-"+d[e]);null!=g&&b(g)}}var d=f(a);d.hasClass(l)&&c.call(a);d.find("."+l).each(c)}function d(a){this.IN=function(){return a}}function c(a,b,c,d,g,f,h){var k=c,m=!1,p={};delete d[g];Object.defineProperty(d,g,{get:function(){if(m||null!=a.fu)return k;var c=f(h?h():g);return e([b,c,k],p)},
set:function(b){k=b;null!=a.fu?p[a.fu]=!0:m=!0},enumerable:!0})}function e(a,b){for(var c=void 0,d=0;d<a.length;d++){var e=a[d];void 0!==e&&(c=f.isPlainObject(e)?g(f.isPlainObject(c)?[c,e]:[e],d==a.length-1?null:b,null):e)}return c}function g(a,b,c){for(var d={},e=a.length,h=0;h<e;h++)for(var k=a[h],m=Object.keys(k),p=0;p<m.length;p++){var n=m[p],l=null==b?null:null==c?n:c+"."+n;if(null==b||!b[l]){var H=k[n];void 0!==H&&(d[n]=f.isPlainObject(H)?g(f.isPlainObject(d[n])?[d[n],H]:[H],b,l):H)}}return d}
function h(){return!0}a.Components={};o_("Components",a.Components,a);a.Components.Tm=function(b){a.Components.WU=f.widget.extend(a.Components.WU||{},b)};o_("Components.setDefaultOptions",a.Components.Tm,a);a.Components.c3=function(){return a.Components.WU||{}};o_("Components.getDefaultOptions",a.Components.c3,a);a.Components.nh=function(a){return new d(a)};o_("Components.createDynamicPropertyGetter",a.Components.nh,a);a.Components.Tf=function(a,b){var c=f(a),d=c.data(k);return d&&(null==b?b=d[0]:
0>d.indexOf(b)&&(b=void 0),null!=b&&(d=c[b],"function"===typeof d))?d.bind(c):null};o_("Components.getWidgetConstructor",a.Components.Tf,a);a.Components.gf=function(c){a.v.L2(c);b(c,function(a){a.wn()})};o_("Components.subtreeAttached",a.Components.gf,a);a.Components.Lg=function(a){b(a,function(a){a.oi()})};o_("Components.subtreeDetached",a.Components.Lg,a);a.Components.Vm=function(c){a.v.L2(c);b(c,function(a){a.Al()})};o_("Components.subtreeShown",a.Components.Vm,a);a.Components.jp=function(a){b(a,
function(a){a.zl()})};o_("Components.subtreeHidden",a.Components.jp,a);a.Components.gO=function(a){var b=a.data(k);return f.isArray(b)&&-1<b.indexOf("ojPopup")&&a.is("."+l)?!0:!1};a.Components.xn="data-oj-container";var k="oj-component-names",l="oj-component-initnode";f.widget("oj.baseComponent",{options:{contextMenu:null,rootAttributes:null,optionChange:void 0,destroy:void 0},refresh:function(){this.$t=null},_createWidget:function(a,b){this.DZ=this.options||{};this.sU=a||{};this._super(a,b);this.LQ()},
pA:function(){var a=this.options.rootAttributes;if(a){var b=this.widget();if(null!=b){var c=a["class"];c&&b.addClass(c);if(c=a.style){var d=b.attr("style");d?b.attr("style",d+";"+c):b.attr("style",c)}a=f.extend({},a);delete a["class"];delete a.style;b.attr(a);delete a.id;a=Object.keys(a);if(a.length)throw Error("Unsupported values passed to rootAttributes option: "+a.toString());}}},_create:function(){this.Qv(this.element);this.ae(this.DZ,this.sU);delete this.DZ;delete this.sU;this._ComponentCreate();
this.rf();this.element.addClass(l)},ae:function(a,b){this.Pla(a,b);this.Rga(b)},_ComponentCreate:function(){var a=this.element,b=this.widgetName,c=a.data(k);c||(c=[],a.data(k,c));0>c.indexOf(b)&&c.push(b)},rf:function(){this.pA();this.Ji=this.eventNamespace+"contextMenu";this.D0(!0)},LQ:f.noop,Qv:function(){},c$:function(a){var b=this;this.HL=[];f.each(a,function(a,c){var d={},e=c.attributes;b.HL.push({element:c,attributes:d});f.each(e,function(a,b){var e=b.name;d[e]={attr:b.value,prop:f(c).prop(e)}})})},
tR:function(a){var b=this.HL;if(void 0===b)return null;a=a[0];for(var c=0,d=b.length;c<d;c++){var e=b[c];if(e.element===a)return e.attributes}return{}},Gs:function(){},H9:function(){f.each(this.HL,function(a,b){var c=f(b.element),d=b.attributes;if(1===c.length){for(var e=b.element.attributes,g=[],h=0,k=e.length;h<k;h++)e[h].name in d||g.push(e[h].name);h=0;for(k=g.length;h<k;h++)c.removeAttr(g[h]);for(var m in d)c.attr(m,d[m].attr)}})},Tz:function(){return this.widgetFullName},Fv:function(a,b,c){return b==
c},A:function(b,c){var d={},e;2<arguments.length?d=Array.prototype.slice.call(arguments,1):2==arguments.length&&(d=arguments[1],"object"===typeof d||d instanceof Array||(d=[d]));e=this.option(n+b);return null==e?b:a.ha.Mb(e.toString(),d)},getNodeBySubId:function(a){return null==a||null==a.subId?this.element?this.element[0]:null:null},getSubIdByNode:function(){return null},destroy:function(){this._trigger("destroy");this.element[0].dispatchEvent(new CustomEvent("_ojDestroy",{bubbles:!1}));this._super();
this.t_();this.element.removeClass(l);this.widget().removeClass("oj-disabled");this.xL(this.element);var a=this.element,b=this.widgetName,c=a.data(k);c&&(b=c.indexOf(b),0<=b&&(c.splice(b,1),0===c.length&&a.removeData(k)));this.Gs();this.hY?this.element.attr("contextmenu",this.hY):this.element.removeAttr("contextmenu");this.$t=null},option:function(a,b){if(0===arguments.length)return f.widget.extend({},this.options);var c=arguments[0],d=c,e=null,g={};if("string"===typeof c){var d={},h=c.split("."),
c=h.shift();if(h.length){var e=h.join("."),k;try{1<arguments.length&&(this.fu=e),k=d[c]=f.widget.extend({},this.options[c])}finally{this.fu=null}for(c=0;c<h.length-1;c++)k[h[c]]=k[h[c]]||{},k=k[h[c]];c=h.pop();if(1===arguments.length)return void 0===k[c]?null:k[c];k[c]=b}else{if(1===arguments.length)return void 0===this.options[c]?null:this.options[c];d[c]=b}g=arguments[2]||g}else g=arguments[1]||g;null!=e&&(g=f.widget.extend({},g,{subkey:e}));(e=g?g._context:null)&&e.Wa?this.oha(d,g):this._setOptions(d,
g);return this},oha:function(a,b){for(var c in a){var d=a[c],e=this.options[c];this.options[c]=d;this.BZ(c,d,e,b)}},_setOptions:function(a,b){for(var c in a)this._setOption(c,a[c],b);return this},_setOption:function(a,b,c){var d=this.options[a];if("disabled"===a)this.options[a]=b,this.widget().toggleClass("oj-disabled",!!b).attr("aria-disabled",b),b&&this.xL(this.widget());else{try{var e=null==c?null:c.subkey;null!=e&&(this.fu=e);this._super(a,b)}finally{this.fu=null}"contextMenu"===a&&this.D0(!1)}this.BZ(a,
b,d,c);return this},BZ:function(a,b,c,d){var e=!1,g=null,h=!1,k=null,m=null,p;d&&(e=d.changed,g=d._context)&&(k=g.originalEvent,h=void 0===g.Hc?null!=k:g.Hc,m=g.Br,p=g.Kj);if(e||!this.Fv(a,c,b))m=m||{},m.writeback=h?"shouldWrite":"shouldNotWrite",a={option:a,previousValue:c,value:b,optionMetadata:m},null!=p&&(a=f.extend({},p,a)),this._trigger("optionChange",k,a)},_trigger:function(a,b,c){return this.CM(a,b,c).proceed},CM:function(a,b,c){var d=this.options[a];c=c||{};b=f.Event(b,p);b.type=(this.widgetEventPrefix+
a).toLowerCase();b.target=this.element[0];this.element.trigger(b,c);return{proceed:!(f.isFunction(d)&&!1===d.apply(this.element[0],[b].concat(c))||b.isDefaultPrevented()),event:b}},Rga:function(a){var b=this.element.attr("contextmenu");this.hY=b;!b||"contextMenu"in a||this.option("contextMenu","#"+b,{_context:{Wa:!0}})},D0:function(b){this.t_();if(this.options.contextMenu){var c=this.widget(),d=this.element;b&&!d.is(c)&&d.removeAttr("contextmenu");(b=f(this.options.contextMenu).attr("id"))&&c.attr("contextmenu",
b);var e=this;this.JZ=function(a){121==a.which&&a.shiftKey&&e.fW().is(":visible")&&a.preventDefault()};var g=!1,h=!1,k,m,p,n=null,l=function(a,b,d){g=d;var f=e.VI();if(g)c.one("touchend"+e.Ji,function(){f.Ls(!0);setTimeout(function(){f.Ls(!1)},50)});"touchstart"===n&&"contextmenu"===a.type||"contextmenu"===n&&"touchstart"===a.type?(n=null,clearTimeout(p)):a.isDefaultPrevented()||a.originalEvent&&a.originalEvent.defaultPrevented||e.be()||(e.uf(f,a,b),!e.fW().is(":visible")||(a.preventDefault(),document.addEventListener("keyup",
e.JZ),"touchstart"!==a.type&&"contextmenu"!==a.type))||(n=a.type,p=setTimeout(function(){n=null},300))};this.gU=function(a){g&&(a.preventDefault(),a.stopPropagation(),g=!1)};c[0].addEventListener("click",this.gU,!0);c.on("touchstart"+this.Ji+" mousedown"+this.Ji+" keydown"+this.Ji+" ",function(a){if("mousedown"!==a.type||!e.VI().Ls()){g=!1;if("touchstart"===a.type&&1===a.originalEvent.touches.length){var b=a.originalEvent.touches[0];k=b.pageX;m=b.pageY;h=!0;this.VH=setTimeout(l.bind(void 0,a,"touch",
!0),750)}return!0}}).on("touchmove"+this.Ji,function(a){a=a.originalEvent.touches[0];if(5<Math.abs(k-a.pageX)||5<Math.abs(m-a.pageY))h=!1,clearTimeout(this.VH);return!0}).on("touchend"+this.Ji+" touchcancel"+this.Ji,function(){h=!1;clearTimeout(this.VH);return!0}).on("keydown"+this.Ji+" contextmenu"+this.Ji,function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&l(a,h?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass(a.v.Ud()?"oj-menu-context-menu-launcher":void 0)}},j0:function(){this.cq=
f(this.options.contextMenu).first();this.XA=this.cq.data("oj-ojMenu");if(!this.XA)throw Error('"contextMenu" option set to "'+this.options.contextMenu+'", which does not reference a valid JET Menu.');var a=this;this.cq.on("ojclose"+this.Ji,function(){document.removeEventListener("keyup",a.JZ)})},VI:function(){this.XA||this.j0();return this.XA},fW:function(){this.cq||this.j0();return this.cq},t_:function(){this.widget().removeAttr("contextmenu").off(this.Ji).removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",
this.gU,!0);this.cq&&this.cq.off(this.Ji);clearTimeout(this.VH);this.cq=this.XA=void 0},uf:function(a,b,c){this.wf(b,c)},wf:function(a,b,c,d,e){b={launcher:this.element,position:{mouse:{my:"start top",at:"start bottom",of:a,collision:"flipfit"},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher",collision:"flipfit"}}[b]};var g={initialFocus:"menu"};c=e?f.extend(b,c,g):f.extend(!0,b,c,g);e=this.VI();e.xA=!0;e.open(a,c,
d);e.xA=!1},xL:function(a){a.removeClass("oj-hover oj-focus oj-active");a.find(".oj-hover").removeClass("oj-hover");a.find(".oj-focus").removeClass("oj-focus");a.find(".oj-active").removeClass("oj-active")},_hoverable:function(a){this._on(a,{mouseenter:function(a){f(a.currentTarget).hasClass("oj-disabled")||f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){f(a.currentTarget).removeClass("oj-hover")}})},_focusable:function(a){this._on(a,{focusin:function(a){f(a.currentTarget).addClass("oj-focus")},
focusout:function(a){f(a.currentTarget).removeClass("oj-focus")}})},Up:function(a){this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")}})},Qp:function(a){if(a){f(a).off(this.eventNamespace);var b=this.bindings;b&&(this.bindings=f(b.not(a)))}},v3:function(a){return this.option(n+a)},dc:function(){return a.v.zm()},wn:function(){this.$t=null},oi:function(){this.$t=null;this.xL(this.widget())},Al:function(){},zl:function(){},
be:function(){return this.options.disabled||this.lT?!0:!1},Wv:function(a){this.lT=a},afa:function(){var b=[],c=this,d=0;this.x1(function(e){e=0==d?c.Tz():e.widgetFullName;d++;var g=a.ha.iE(e);null==g||f.isEmptyObject(g)||b.push(e)});var e=b.length;return 0<e?function(){if(1==e)return a.ha.iE(b[0]);for(var c={},d=e-1;0<=d;d--)f.widget.extend(c,a.ha.iE(b[d]));return c}:null},Xda:function(){if(!this.$t){var b={};this.$t=b;for(var c=this.element[0],d=c,e=[];d;){var g=d.getAttribute,g=g?g.call(d,a.Components.xn):
null;null!=g&&e.push(g);d=d.parentNode}b.containers=e;b.element=c}return this.$t},Pla:function(a,b){var d=this.options,e=this.afa(),g=b[m];null==e||void 0!==g&&!f.isPlainObject(g)||c(this,void 0,b[m],d,m,e);this.aia(a,b)},aia:function(b,g){var h=this.options,k={},m=[];this.x1(function(a){m.push(a.widgetName)});var p=a.Components.c3();m.push("default");for(var n=m.length-1;0<=n;n--){var l=p[m[n]];void 0!==l&&(k=f.widget.extend(k,l))}if(!f.isEmptyObject(k)){var y=this,p=function(){return y.Xda()},C;
for(C in k)if(n=g[C],void 0===n||f.isPlainObject(n))l=k[C],null!=l&&l instanceof d?(l=l.IN(),f.isFunction(l)?c(this,b[C],n,h,C,l,p):a.q.error("Dynamic getter for property %s is not a function",C)):h[C]=e([b[C],l,n])}},x1:function(a){for(var b=this.constructor.prototype;null!=b&&"oj"===b.namespace;)a(b),b=Object.getPrototypeOf(b)}});delete f.fn.baseComponent;a.ya=function(a,b,c,d){f.widget(a,b,c);d&&delete f.fn[a.split(".")[1]];if("oj.oj"===a.substring(0,5)||"oj._oj"===a.substring(0,6)){b=a.split(".");
a=b[0];b=b[1];var e=a+"-"+b;f.expr[":"][("_"===b.substring(0,1)?"_"+a+"-"+b.substring(3):a+"-"+b.substring(2)).toLowerCase()]=function(a){return!!f.data(a,e)}}};var m="translations",n=m+".",p={preventDefault:function(){this.isDefaultPrevented=h},stopPropagation:function(){this.isPropagationStopped=h},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=h}};a.Ta=function(a){this.Init(a)};a.b.ga(a.Ta,a.b,"oj.ComponentMessaging");a.Ta.gd={NONE:"none",Bz:"notewindow",pv:"placeholder",
lv:"inline"};a.Ta.cG={};a.Ta.OE=function(b,c){b&&"function"===typeof c&&(a.Ta.cG[b]=c)};a.Ta.prototype.Init=function(b){a.Ta.r.Init.call(this);this.ka=b;this.Yv=!1;this.kha()};a.Ta.prototype.Go=function(b,c){var d=this;a.l.Kf(c);this.kc=b;this.EC=a.zc.Lf(this.EC||{},c);this.Yv?this.Fja():(f.each(this.Wq,function(a,b){b.Go(d)}),this.Yv=!0)};a.Ta.prototype.update=function(b){a.l.Kf(b);a.l.V1(this.Yv);this.EC=a.zc.Lf(this.EC||{},b);this.Yv&&f.each(this.Wq,function(a,c){c.hP(b)&&c.update()})};a.Ta.prototype.Vk=
function(){f.each(this.Wq,function(a,b){b.Vk()});this.Yv=!1;this.kc=this.ka=null;this.Wq={}};a.Ta.prototype.tw=function(b,c){return new (a.Ta.cG[b]||a.Ta.cG[a.Ta.gd.NONE])(c)};a.Ta.prototype.Pda=function(){return this.ka||null};a.Ta.prototype.rea=function(){return this.kc||null};a.Ta.prototype.xi=function(){return this.EC||{}};a.Ta.prototype.VW=function(){var b={},c=!1,d,e,g=this.ka.options.placeholder,h,k,m,p,n=this.ka.options.displayOptions||{},l={};k=Object.keys(n);for(m=0;m<k.length;m++){e=k[m];
d=n[e];c=!1;h=e+"";if(Array.isArray(d))for(p=0;p<d.length;p++)e=d[p],c||(c=this.O_(h,e,g,l));else"string"===typeof d&&(c||(c=this.O_(h,d,g,l)));c||(l[h]=a.Ta.gd.NONE)}f.each(a.Ta.gd,function(a,c){b[c]=[]});f.each(l,function(a,c){b[c].push(a)});return b};a.Ta.prototype.O_=function(b,c,d,e){var g=!1;switch(c){case a.Ta.gd.pv:"converterHint"!==b||g||d||(e[b]=c,g=!0);break;case a.Ta.gd.lv:"messages"!==b||g||(e[b]=c,g=!0);break;default:g||(e[b]=c,g=!0)}return g};a.Ta.prototype.kha=function(){var b=this.VW(),
c=b[a.Ta.gd.Bz],d=b[a.Ta.gd.NONE],e=b[a.Ta.gd.pv],b=b[a.Ta.gd.lv],g={};0<c.length&&(g[a.Ta.gd.Bz]=this.tw(a.Ta.gd.Bz,c));0<e.length&&(g[a.Ta.gd.pv]=this.tw(a.Ta.gd.pv,e));0<b.length&&(g[a.Ta.gd.lv]=this.tw(a.Ta.gd.lv,b));g[a.Ta.gd.NONE]=this.tw(a.Ta.gd.NONE,d);this.Wq=g};a.Ta.prototype.Fja=function(){var b=this.VW(),c,d=this;f.each(b,function(b,e){b+="";c=d.Wq[b];e&&0<e.length?c?c&&c.Er(e):(c=d.tw(b,e),d.Wq[b]=c,c.Go(d)):c&&a.Ta.gd.NONE!==b&&(c.Vk(),delete d.Wq[b])})};a.nc=function(a){this.Init(a)};
a.b.ga(a.nc,a.b,"oj.MessagingStrategy");a.nc.prototype.Init=function(b){a.l.QD(b);a.nc.r.Init.call(this);this.iB=b};a.nc.prototype.Go=function(a){this.bq=a};a.nc.prototype.Vk=function(){};a.nc.prototype.Er=function(a){this.Init(a)};a.nc.prototype.hP=function(){return!0};a.nc.prototype.update=function(){};a.nc.prototype.ai=function(){return this.bq.rea()};a.nc.prototype.Zi=function(){return this.bq.Pda()};a.nc.prototype.pF=function(){return this.rF().qx};a.nc.prototype.oF=function(){return this.rF().Hu()};
a.nc.prototype.WP=function(){var a=[],b=this.xi();(b=b&&b.q2)&&a.push(b);return a};a.nc.prototype.P6=function(){var a=[],b=this.xi();f.each(b&&b.mra||[],function(b,c){a.push(c)});return a};a.nc.prototype.O6=function(){var a=this.xi();return a&&a.title||""};a.nc.prototype.rF=function(){var a=this.xi();return a&&a.n6||null};a.nc.prototype.xF=function(){var a=this.pF();return a&&0<a.length?!0:!1};a.nc.prototype.AQ=function(){return-1!==this.iB.indexOf("messages")?!0:!1};a.nc.prototype.JF=function(){return-1!==
this.iB.indexOf("converterHint")?!0:!1};a.nc.prototype.CQ=function(){return-1!==this.iB.indexOf("validatorHint")?!0:!1};a.nc.prototype.BQ=function(){return-1!==this.iB.indexOf("title")?!0:!1};a.nc.prototype.S6=function(){return this.rF().lO()};a.nc.prototype.xi=function(){return this.bq?this.bq.xi():{}};a.jf=function(a){this.Init(a)};a.Ta.OE(a.Ta.gd.NONE,a.jf);a.jf.mA="oj-invalid";a.jf.nA="oj-warning";a.b.ga(a.jf,a.nc,"oj.DefaultMessagingStrategy");a.jf.prototype.update=function(){a.jf.r.update.call(this);
var b=this.ai(),c=this.oF(),d=[],e=[],g=!1,f=this.Zi().widget();b&&(this.S6()?(d.push(a.jf.nA),e.push(a.jf.mA),g=!0):this.xF()&&c===a.X.Tb.WARNING?(d.push(a.jf.mA),e.push(a.jf.nA)):(d.push(a.jf.mA),d.push(a.jf.nA)),f.removeClass(d.join(" ")).addClass(e.join(" ")),b.attr({"aria-invalid":g}))};a.jf.prototype.Vk=function(){this.Zi().widget().removeClass(a.jf.mA).removeClass(a.jf.nA);this.ai().removeAttr("aria-invalid");a.jf.r.Vk.call(this)};a.xh=function(a){this.Init(a)};a.Ta.OE(a.Ta.gd.pv,a.xh);a.b.ga(a.xh,
a.nc,"oj.PlaceholderMessagingStrategy");a.xh.prototype.Init=function(b){a.xh.r.Init.call(this,b)};a.xh.prototype.Go=function(b){a.xh.r.Go.call(this,b);this.pL()};a.xh.prototype.Er=function(b){a.xh.r.Er.call(this,b);this.pL()};a.xh.prototype.hP=function(a){return a&&void 0!==a.q2?!0:!1};a.xh.prototype.update=function(){a.xh.r.update.call(this);this.pL()};a.xh.prototype.pL=function(){var a=this.ai();this.q7()&&a&&(a=this.WP(),a=a.length?a[0]:"",this.Zi().option({placeholder:a},{_context:{Epa:!0}}))};
a.xh.prototype.q7=function(){return this.JF()};a.Ui=function(a,b){this.Init(a,b)};a.Ui.lO=function(b){return a.X.Hu(b)>=a.X.Tb.ERROR?!0:!1};a.b.ga(a.Ui,a.b,"oj.ComponentValidity");a.Ui.prototype.Init=function(b,c){a.Ui.r.Init.call(this);this.iY(c)};a.Ui.prototype.lO=function(){return this.fo};a.Ui.prototype.Hu=function(){return this.lia};a.Ui.prototype.update=function(a,b){this.iY(b)};a.Ui.prototype.iY=function(b){this.lba=b;this.qx=this.lea();this.lia=a.X.Hu(this.qx);this.fo=a.Ui.lO(this.qx)};a.Ui.prototype.lea=
function(){for(var b=this.lba||[],c=[],d,e=0;e<b.length;e++)d=b[e],d instanceof a.Ic&&!d.c2()||c.push(d);return c};a.v={};a.v.u8="\x3chtml\x3e";a.v.t8="\x3c/html\x3e";a.v.N8={SPAN:1,B:1,I:1,EM:1,BR:1,HR:1,LI:1,OL:1,UL:1,P:1,TT:1,BIG:1,SMALL:1,PRE:1};a.v.M8={"class":1,style:1};a.v.Gpa=function(b){return 0===b.indexOf(a.v.u8)&&b.lastIndexOf(a.v.t8)===b.length-7?!0:!1};a.v.Fna=function(b){var c=f(document.createElement("span")).get(0);(c.innerHTML=b)&&0<=b.indexOf("\x3c")&&a.v.XT(c);return c};a.v.XT=
function(b){for(var c=b.childNodes,d,e,g,h,k,m=c.length-1;0<=m;){if((d=c.item(m))&&1===d.nodeType)if(a.v.N8[d.nodeName]){e=d.attributes;for(k=e.length-1;0<=k;k--)g=e[k],(h=void 0!==f(d).attr(g.name))&&(a.v.M8[g.name]||d.removeAttribute(g.nodeName));a.v.XT(d)}else d&&b.removeChild(d);m--}};a.v.bl=function(a,b){for(var c=b.parentNode;c;){if(c==a)return!0;c=c.parentNode}return!1};a.v.To=function(b,c){return c==b?!0:a.v.bl(b,c)};a.v.Ph=function(b,c,d){var e=f(b),g=e.data(a.v.Ov);null==g&&(g=new a.v.G9(b),
e.data(a.v.Ov,g),g.start());g.addListener(c,d)};a.v.Si=function(b,c){var d=f(b),e=d.data(a.v.Ov);null!=e&&(e.removeListener(c),e.ph()&&(e.stop(),d.removeData(a.v.Ov)))};a.v.L2=function(b){f(b).find(".oj-helper-detect-expansion").parent().each(function(b,c){var d=f(c).data(a.v.Ov);null!=d&&d.Em(!0)})};a.v.Fm=function(b){var c=a.Na.Fy();return a.Na.aj.iQ===c.os?b.metaKey:b.ctrlKey};a.v.pha=(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,
0)}).bind(window);a.v.RT=(window.cancelAnimationFrame||window.mozCancelAnimationFrame||window.webkitCancelAnimationFrame||function(a){return window.clearTimeout(a)}).bind(window);a.v.G9=function(b){function c(a){var b=!1;if(null!=E.offsetParent){var e=E.offsetWidth,g=E.offsetHeight;if(F!==e||G!==g)l=n,h(e,g),b=!0,a&&d(!0)}return b}function d(c){var e=b.offsetWidth,g=b.offsetHeight;k.has()&&(c?(null!==H&&a.v.RT(H),H=a.v.pha(function(){H=null;k.fire(e,g)})):k.fire(e,g));for(c=0;c<m.length;c++)m[c].IN()(e,
g)}function e(a){a.stopPropagation();!c(!0)&&0<l&&null!=E.offsetParent&&(0==E.scrollLeft||0==E.scrollTop)&&(l--,h(F,G))}function g(){d(!1)}function h(a,b){F=a;G=b;var c=E.firstChild.style,d=1;do c.width=a+d+"px",c.height=b+d+"px",E.scrollLeft=E.scrollTop=d,d++;while((0==E.scrollTop||0==E.scrollLeft)&&5>=d);B.scrollLeft=a;B.scrollTop=b}var k=f.Callbacks(),m=[],p=[],n=2,l=0,H=null,F=null,G=null,E=null,B=null,z=null,L=null;this.addListener=function(b,c){void 0===c||0===c?k.add(b):(m.push(new a.v.kba(b,
c)),p.push(b))};this.removeListener=function(a){var b=p.indexOf(a);0<=b?(p.splice(b,1),m.splice(b,1)[0].stop()):k.remove(a)};this.ph=function(){return!k.has()&&0==p.length};this.start=function(){L=e.bind(this);if(b.attachEvent)z=g.bind(this),b.attachEvent("onresize",z);else{var a=b.childNodes[0];E=document.createElement("div");E.className="oj-helper-detect-expansion";var c=document.createElement("div");E.appendChild(c);null!=a?b.insertBefore(E,a):b.appendChild(E);E.addEventListener("scroll",L,!1);
B=document.createElement("div");B.className="oj-helper-detect-contraction";a=document.createElement("div");a.style.width="200%";a.style.height="200%";B.appendChild(a);b.insertBefore(B,E);B.addEventListener("scroll",L,!1);this.Em(!1)}};this.stop=function(){null!=H&&(a.v.RT(H),H=null);null!=E?(E.removeEventListener("scroll",L),B.removeEventListener("scroll",L),b.removeChild(E),b.removeChild(B)):b.detachEvent("onresize",z)};this.Em=function(a){var b=c(a);a&&!b&&null!=E.offsetParent&&h(F,G)}};a.v.Ov=
"_ojResizeTracker";a.v.vE=function(a){return/^[A-Za-z][0-9A-Z_a-z-]*$/.test(a)};a.v.kba=function(a,b){function c(){e=Array.prototype.slice.call(arguments);null==g&&(g=window.setTimeout(d,b))}function d(){a.apply(null,e);g=null}var e=null,g=null;this.IN=function(){return c};this.stop=function(){null!=g&&(window.clearTimeout(g),g=null)}};a.v.Ud=function(){return"ontouchstart"in window||0<navigator.msMaxTouchPoints||0<navigator.maxTouchPoints};a.v.A5=function(b){a.v.Sha=b};a.v.unwrap=function(b,c){var d=
a.v.Sha;d&&d==b.parent().get(0)||(1<arguments.length?c.replaceWith(b):b.unwrap())};a.v.g4=function(b){function c(b){var d=b.target,e=f(d),g=d.getBoundingClientRect(),h=a.v.nE(),q="ltr"===a.v.zm();return q&&("HTML"===d.nodeName||"visible"!==e.css("overflow-x"))&&b.clientX>g.right-h?!0:!q&&"HTML"===d.nodeName&&b.clientX>g.left-h?!0:!q&&"visible"!==e.css("overflow-x")&&b.clientX<g.left+h?!0:("HTML"===d.nodeName||"visible"!==e.css("overflow-y"))&&b.clientY>g.bottom-h?!0:!1}if(!("clientX"in b&&"clientY"in
b))return!1;var d=a.Na.Fy();if(a.Na.aj.CP===d.os||a.Na.aj.zF===d.os)b=!1;else{var e;if(a.Na.cn.RP===d.engine)try{e=b.originalTarget.localName?!1:!0}catch(g){e=!0}else e=a.Na.cn.PF===d.engine?c(b):a.Na.sl.yF===d.browser?c(b):!1;b=e}return b};a.v.nE=function(){var b=a.v.Zka;if(f.isNumeric(b))return b;b=f("\x3cdiv /\x3e");f(document.body).append(b);b.width(50).height(50).css({overflow:"scroll",visibility:"hidden",position:"absolute"});var c=f("\x3cdiv /\x3e");c.height(1);b.append(c);var c=c.width(),
d=b.width();b.remove();return b=a.v.Zka=d-c};a.v.zm=function(){var a=document.documentElement.getAttribute("dir");a&&(a=a.toLowerCase());return"rtl"===a?"rtl":"ltr"};a.v.wm=function(a){return isNaN(a)?a&&0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0:a};a.v.Eoa=function(a){return isNaN(a)?a&&0<a.length?(a=parseFloat(a),isNaN(a)&&(a=0),a):0:a};a.v.Kpa=function(b){function c(b,d){if(-1<["hidden","scroll","auto"].indexOf(d.overflowY)){if(-1>b.bottom-d.top)return!1;var e="auto"===d.overflowX||
"scroll"===d.overflowX?a.v.nE():0;if(1>d.bottom-e-b.top)return!1}if(-1<["hidden","scroll","auto"].indexOf(d.overflowX)){e="auto"!==d.overflowY&&"scroll"!==d.overflowY||"rtl"!==a.v.zm()?0:a.v.nE();if(-1>b.right-(d.left+e))return!1;e="auto"!==d.overflowX&&"scroll"!==d.overflowX||"ltr"!==a.v.zm()?0:a.v.nE();if(-1<b.left-(d.right-e))return!1}return!0}function d(a){return"visible"!==a.css("overflow-x")||"visible"!==a.css("overflow-y")}function e(a){var b=a[0];return 1===b.nodeType?(b=f.extend({},b.getBoundingClientRect()),
b.overflowX=a.css("overflow-x"),b.overflowY=a.css("overflow-y"),b):f.isWindow(b)?b={width:b.innerWidth,height:b.innerHeight,top:0,bottom:b.innerHeight,left:0,right:b.innerWidth}:{height:0,width:0}}function g(b){return-1<["fixed","absolute","relative"].indexOf(b.css("position"))&&(0<Math.abs(a.v.wm(b.css("top")))||0<Math.abs(a.v.wm(b.css("bottom")))||0<Math.abs(a.v.wm(b.css("left")))||0<Math.abs(a.v.wm(b.css("right"))))}if(!b)return!1;if(f.isWindow(b[0])||g(b))return!0;var h=e(b),k=!0;for(b=b.parent();k&&
b&&0<b.length&&"BODY"!==b[0].nodeName&&1===b[0].nodeType&&!g(b);){if(d(b)){var m=e(b);0<m.height&&0<m.width&&(k=c(h,m))}b=b.parent()}return k};a.v.kG="oj-logical-parent";a.v.Ioa=function(b){if(b)return b.data(a.v.kG)};a.v.B5=function(b,c){b&&(null===c?b.removeData(a.v.kG):b.data(a.v.kG,c))};a.v.Ipa=function(b,c){a.l.$M(b);a.l.$M(c);for(var d=c;d;){if(d==b)return!0;var e=a.v.Ioa(f(d)),d=e?e[0]:d.parentNode}return!1};a.v.jra=function(a){var b=document.createElement("a");b.href=a;a=b.protocol;null!=
a&&(a=a.toLowerCase());if(0>["http:","https:"].indexOf(a))throw a+" is not a valid URL protocol";};a.v.ima=function(){f(document.body).hasClass("oj-hybrid")&&document.body.addEventListener("contextmenu",function(a){a.preventDefault()},!0)};a.v.ima();a.ud={};a.ud.uS=":tabbable";a.ud.UD=function(b){var c=document.activeElement;return b&&c?a.v.To(b,c):!1};a.ud.Ey=function(a){a.focus()};a.ud.DN=function(b){(b=a.ud.j3(b))&&a.ud.Ey(b)};a.ud.j3=function(b){var c=f(b);return c.is(a.ud.uS)?b:(b=c.find(a.ud.uS))&&
0<b.length?b[0]:null};f(document).ready(function(){var a=f("\x3cdiv style\x3d'border: 1px solid;border-color:red green;position: absolute;top: -999px;background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs\x3d);'\x3e\x3c/div\x3e"),b;a.appendTo("body");b=a.css("backgroundImage");a.css("borderTopColor")!=a.css("borderRightColor")&&(null==b||"none"!=b&&"url (invalid-url:)"!=b)||f("body").addClass("oj-hicontrast");a.remove()});f(document).ready(function(){"Microsoft Internet Explorer"==
navigator.appName&&f("html").addClass("oj-slow-borderradius oj-slow-cssgradients oj-slow-boxshadow")});a.dj={};o_("Test",a.dj,a);a.dj.ready=!1;o_("Test.ready",a.dj.ready,a);a.dj.moa=function(b){var c=b;if(a.Ea.qd(b))try{c=f.parseJSON(b)}catch(d){return null}return c&&c.element&&(b=f(c.element))?(b=a.Components.Tf(b[0],c.component),delete c.element,b("getNodeBySubId",c)):null};o_("Test.domNodeForLocator",a.dj.moa,a);a.dj.SN=function(){return a.J.SN()};o_("Test.getOpenPopupCount",a.dj.SN,a);a.dj.vN=
function(){return a.J.vN()};o_("Test.findOpenPopups",a.dj.vN,a);a.dj.lN=function(b,c){return a.J.lN(b,c)};o_("Test.compareStackingContexts",a.dj.lN,a)});