/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(a,f,b){var d={w6:1,GP:2,JP:3,oQ:4,pQ:5,qQ:6,k7:7,s7:8,GQ:9,HQ:10,v7:11},c={Lo:!0,Ti:d.GP},e={Lo:!0,Ti:d.JP},g={Lo:!0,Ti:d.qQ},h={Lo:!0,Ti:d.oQ},k={Lo:!0,Ti:d.pQ},l={Lo:!0,Ti:d.HQ};a.ya("oj.editableValue",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:null,source:null},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,
required:!1,title:"",validators:void 0,value:void 0},getNodeBySubId:function(a){return this._super(a)},isValid:function(){void 0===this.RM&&(this.RM=this.bfa());return this.RM},refresh:function(){this._super();this.mV(!0)},reset:function(){this.TA();this.Wx(this.ij.k7);this.oL(this.options.value,!0)},showMessages:function(){var b=this.options.messagesHidden,c,d=!1,e,g=[];for(e=0;e<b.length;e++)d=!0,c=b[e],c instanceof a.Ic&&c.wda(),g.push(c.clone());d&&(this.mw("messagesHidden"),this.DD("messagesShown",
g))},validate:function(){return this.gc(this.kg(),null,this.tA)},Uv:{PP:1,u7:2,rQ:3},ij:d,tA:{jr:!1,Ti:d.GQ},ae:function(a,b){this._super(a,b)},_ComponentCreate:function(){var a=this.element,b=this.tR(a);this._super();this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=[];this.options.messagesShown=0<this.options.messagesCustom.length?this.eba(this.options.messagesCustom):[];this.EG(a);this.Hp()&&(this.Cn(this.options.placeholder),this.hI=!0);f.each(["required",
"title"],function(c,d){d in b&&a.removeAttr(d)})},rf:function(){this._super();this.Oba();this.mV(!1);this.pC();this.Wx(this.ij.w6);0<this.options.messagesShown.length&&this.Zx("messagesShown",this.options.messagesShown,null,!0);this.widget().addClass("oj-form-control")},Qv:function(a){this.c$(a)},Gs:function(a){this.H9(a)},MQ:function(a,b){switch(a){case "disabled":this.NQ(a,e);break;case "converter":this.z7(a);break;case "displayOptions":this.pC();break;case "help":this.Xg(a,this.options[a]);break;
case "messagesCustom":this.sia(b);break;case "placeholder":this.dja(b);break;case "readOnly":this.NQ(a,h);break;case "required":this.A7(a);break;case "title":this.xma();break;case "translations":this.refresh();break;case "value":this.B7(a,b);break;case "validators":this.ks(a)}},z7:function(a){var b=!1;this.F9();this.hC()&&(b=!0);b?(this.UA(),this.FD(c)):this.Xg(a,this.options[a],!0)},NQ:function(a,b){var c=!this.options[a];this.Xg(a,this.options[a]);c&&this.U_(b)},A7:function(a){this.Xg(a,this.options[a]);
this.U_(g)},B7:function(a,b){var c=!1,d,e=b?b._context:null;e&&(c=e.originalEvent?!0:!1,d=e.Lo||!1);c||(d||this.TA(null),this.Wx(this.ij.v7));this.Xg(a,this.options[a],!0)},ks:function(){var a=!1;this.pS();this.hC()&&(a=!0);a&&(this.UA(),this.FD(l))},Ev:function(){var a=this.options.readOnly||!1;return this.options.disabled||a?!1:!0},_destroy:function(){this.widget();var b=this._super();this.TA(null,!0);this.nt().Vk();this.Rb&&null!=a.Components.Tf(this.Rb[0])&&this.Rb._ojLabel("destroy");return b},
Focus:function(){this.$d().focus();return!0},_setOption:function(b,c,d){var e;e=!1;if("string"===typeof b&&void 0!==c)switch(b){case "messagesHidden":e=!0;break;case "messagesShown":e=!0;break;case "rawValue":e=!0}if(e)return a.q.error(b+" option cannot be set"),this;e=this._superApply(arguments);this.MQ(b,d);return e},$d:function(){return this.element},q8:function(){var a=this.UV(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=f("label[for\x3d'"+a+"']"),
0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=this.UV(a),null!==a&&0!==a.length)?a:null},vs:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.$d()},Tc:function(){this.Jc||(this.Jc=a.sb.getConverterInstance(this.options.converter));return this.Jc||null},Iv:function(){this.XX||(this.XX={});return this.XX},kg:function(){return this.$d().val()},rR:function(){if(!this.$v){var b=[],c=this.options.validators,d,e=!0,g=this.Iv(),
f=[],h,k;k=Object.keys(g);h=k.length;if(0<h){for(var l=0;l<h;l++)d=k[l],f.push(g[d]);b=b.concat(f)}if(c){f=[];for(k=0;k<c.length;k++)d=c[k],"object"===typeof d?(d.validate&&"function"===typeof d.validate||(e=!1),e||(h=d.type)&&"string"===typeof h&&((g=a.qa.Or(h))?(d=a.zc.Lf({},d.options)||{},d.converter=d.converter||this.Tc(),d.label=d.label||this.hJ(),d=g.createValidator(d)):a.q.error("Unable to locate a validatorFactory for the requested type: "+h)),f.push(d)):a.q.error("Unable to parse the validator provided:"+
d);b=b.concat(f)}this.$v=b}return this.$v||[]},pS:function(){this.$v&&(this.$v.length=0);this.$v=null;this.nt().update(this.xi(this.Ch.IQ))},F9:function(){this.Jc=null;this.nt().update(this.xi(this.Ch.FP))},sn:function(){return this.options.required},Uz:function(a){var b=this.kg();this.gc(b,a)},Dn:function(a,b){var c={};c._context={originalEvent:b,Hc:!0,Wa:!0};this.options.rawValue!==a&&this.option("rawValue",a,c)},Xg:function(a,b,c){switch(a){case "converter":b=this.options.value;this.oL(b,c);break;
case "disabled":this.j_("disabled",this.options.disabled);break;case "help":b=this.options.help.definition;c=this.options.help.source;a=this.OI();this.Rb&&(this.Rb._ojLabel("option","describedById",a),this.Rb._ojLabel("option","help",{definition:b,source:c}));break;case "required":this.j_("required",this.sn());this.AG(b);this.Rb&&(a=this.OI(),this.Rb._ojLabel("option",{describedById:a,ariaRequiredUnsupported:this.Iz()}),this.Rb._ojLabel("option","required",b));break;case "value":this.oL(b,c)}},AG:function(a){var b=
this.$d();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},Iz:function(){return!1},BG:function(){this.Rb&&this.Rb._ojLabel("refresh");this.Jc=this.nK=null;this.pS()},qi:function(a){var b=this.$d();b.val()!==a&&b.val(a)},EG:function(a){"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled)},Cn:function(a){this.$d().attr("placeholder",a)},tS:function(a){this.options.placeholder=a},Hp:function(){return this.options.placeholder},$Q:function(){this.tS("");this.Cn("")},
gc:function(b,c,d){var e=d&&"boolean"===typeof d.jr?d.jr:!0;if(void 0===b)return a.q.warn("Attempt to set a value of undefined"),!1;if(e&&b===this.oea())a.q.bz>a.q.hn&&a.q.info("Validation skipped and value option not updated as submitted value '"+b.toString?b.toString():b+" same as previous.");else if(b=this.US(b,c,d),void 0!==b&&this.isValid()){var g;d&&d._context&&(g=d._context);this.F1(b,c,d&&d.Ti,g);return!0}return!1},US:function(b,c,d){var e=d&&d.lra?d.lra:this.Uv.PP,g=d&&d.Ti?d.Ti:this.ij.s7;
d=d&&d.Lo||!1;if(void 0===b)a.q.warn("Attempt to set a value of undefined");else if(this.Ev()){d||this.TA(c);this.q0(b);try{return this.Uka(b,e,g,c)}catch(f){}}else a.q.bz>a.q.hn&&a.q.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},Fv:function(b,c,d){return"value"===b?a.b.mh(c,d):0===b.indexOf("messages")?this.tia(c,d):this._superApply(arguments)},_GetDefaultStyleClass:function(){a.l.Yb();
return""},Ch:{bv:1,JQ:2,FP:3,IQ:4,EQ:5},Bn:{disabled:"oj-disabled",required:"oj-required"},TA:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.mw("messagesHidden",a),this.mw("messagesShown",a),this.mw("messagesCustom",a))},UA:function(){var b=this.options.messagesShown,c=b.length,d;this.mw("messagesHidden");for(var e=c-1;0<=e;e--)d=b[e],d instanceof a.Ic&&b.splice(e,1);b.length!==c&&this.Zx("messagesShown",b,null,!0)},Zx:function(a,
b,c,d){var e={},g=0===b.length&&0===this.options[a].length;if(d||!g)e._context={originalEvent:c,Hc:!0,Wa:!0},e.changed=d||!g,this.Jka(),this.option(a,b,e),this.Vma()},mw:function(a,b){this.Zx(a,[],b)},eba:function(b){var c,d=[],e;if(b&&0<b.length)for(e=0;e<b.length;e++)c=b[e],c instanceof a.X?d.push(c.clone()):(c=new a.X(c.summary,c.detail,c.severity),c=Object.freeze?Object.freeze(c):c,d.push(c));return d},Oba:function(){if(this.Rb=this.q8()){var a=this.options.help.definition,b=this.options.help.source,
c=this.Iz(),d=this.u$(b,a,this.options.required,c);this.Rb._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:d,required:this.options.required,ariaRequiredUnsupported:c,help:{definition:a,source:b}})}},mV:function(a){var b=!1;a?(this.BG(),this.pC(),this.hC()&&(b=!0),this.UA(),b?this.FD(k):(this.sn()&&this.Wx(k.Ti),this.Xg("value",this.options.value,!0))):(this.Xg("value",this.options.value),this.Xg("required",this.options.required));this.Xg("disabled",this.options.disabled)},
Yra:function(){return this.vZ},oea:function(){void 0===this.TK&&(this.TK="");return this.TK},UV:function(a){a=a.attr("aria-labelledby");return void 0!==a?f("label[id\x3d'"+a+"']"):null},OI:function(){this.element.uniqueId();return this.element.prop("id")+"Icons"},u$:function(a,b,c,d){var e=this.OI();(a||b||c&&d)&&this.XG(e);return e},XG:function(a){this.$d().each(function(){var b=f(this).attr("aria-describedby");b?f(this).attr("aria-describedby",b+" "+a):f(this).attr("aria-describedby",a)})},RB:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},
hJ:function(){if(this.Rb)return this.Rb.text()},pX:function(){this.I1||(this.I1=new a.Ui(this.isValid(),this.RB()));return this.I1},fK:function(){return!a.X.isValid(this.RB())},hC:function(){return!this.isValid()&&0<this.options.messagesShown.length},Bga:function(){for(var b=this.options.messagesShown,c,d,e=0;e<b.length;e++)c=b[e],c instanceof a.Ic&&c.zY()&&(d=d||[],d.push(c));return void 0===d?!1:!a.X.isValid(d)},pC:function(){var a=this.nt(),b=this._GetMessagingLauncherElement(),c=this.xi(this.Ch.bv);
this.hI||this.$Q();a.Go(b,c)},sia:function(b){var c=this.options.messagesCustom,d=[],e,g,f=this.options.messagesShown,h=b?b._context:null;for(g=0;g<f.length;g++)e=f[g],e instanceof a.Ic&&e.zY()&&d.push(e);for(g=0;g<c.length;g++)d.push(c[g]);this.Zx("messagesShown",d,h?h.originalEvent:null,b&&b.changed)},dja:function(a){a=(a&&a._context||{}).Epa?!1:!0;this.Cn(this.options.placeholder);a?(this.hI=!0,this.Tc()&&this.pC()):this.hI=!1},vla:function(a){this.vZ=a},q0:function(a){this.TK=a},xma:function(){this.nt().update(this.xi(this.Ch.EQ))},
DD:function(a,b,c){var d,e,g;if("object"===typeof b&&Array.isArray(b))for(g=this.options[a],d=b.length,e=0;e<d;e++)g.push(b[e]);this.Zx(a,g,c,!0)},Vma:function(){this.nt().update(this.xi())},F1:function(a,b,c,d){d=d||{};b&&(d.originalEvent=b);switch(c){case this.ij.GP:case this.ij.JP:case this.ij.oQ:case this.ij.pQ:case this.ij.qQ:case this.ij.GQ:case this.ij.HQ:d.Hc=!0,d.Lo=!0}this.option({value:a},{_context:d})},Jka:function(){this.RM=void 0},bfa:function(){var a=this.RB(),b=!0;a&&0!==a.length&&
(b=!this.fK());return b},iq:function(b){var c=b,d=this.Tc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(b):a.q.bz>a.q.hn&&a.q.info("converter does not support the format method."));return c},nt:function(){this.bq||(this.bq=new a.Ta(this));return this.bq},kea:function(a){var b,c=[];b="";var d;this.sn()&&(b=this.vW(),b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&
(b=b.getHint())&&c.push(b);return c},vW:function(){var b;b={};var c;null==this.nK&&(b=this.options.translations?this.options.translations.required||{}:{},c={hint:b.hint||null,label:this.hJ(),messageSummary:b.messageSummary||null,messageDetail:b.messageDetail||null},this.nK=(b=a.qa.Or(a.fd.VALIDATOR_TYPE_REQUIRED))?b.createValidator(c):null);return this.nK},xi:function(a){var b={},c=this.Tc(),d="",e=[];a=a||this.Ch.JQ;if(a===this.Ch.bv||a===this.Ch.JQ)e=this.RB(),this.pX().update(this.isValid(),e),
b.n6=this.pX();if(a===this.Ch.bv||a===this.Ch.FP)c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(d=c.getHint()||""),b.q2=d;if(a===this.Ch.bv||a===this.Ch.IQ)c=this.rR(),e=this.kea(c)||[],b.mra=e;if(a===this.Ch.bv||a===this.Ch.EQ)b.title=this.options.title||"";return b},tia:function(b,c){var d=-1,e,g=!0,h=f.extend([],b),k=f.extend([],c);if(h.length!==k.length)return!1;f.each(h,function(b,c){c instanceof a.X?e=c:(e=new a.X(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):
e);d=-1;f.each(k,function(a,b){e.Mo(b)&&(d=a)});-1<d?k.splice(d,1):g=!1});return g},MC:function(b){var c=this.Tc(),d=b;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(b):a.q.bz>a.q.hn&&a.q.info("converter does not support the parse method."));return d},$G:function(b,c){var d,e,g;b instanceof a.Qe||b instanceof a.Ah?(d=b.Iu(),a.l.$c(d,a.X),g=d.severity,e=d.summary,d=d.detail):(g=a.X.Tb.ERROR,e=a.ha.A("oj-message.error"),d=b.message||a.ha.A("oj-converter.detail"));c.push({summary:e,
detail:d,severity:g})},gL:function(b,c,d){var e={},g=[],f=b.qx||[];e.context=c||0;e.display=d||a.Ic.Sr.GF;0===f.length&&this.$G(b,f);for(c=0;c<f.length;c++)b=f[c],g.push(this.Bba(b.summary,b.detail,b.severity,e));return g||null},Bba:function(b,c,d,e){b=new a.Ic(b,c,d,e);return b=Object.seal?Object.seal(b):b},oL:function(a,b){var c=a||this.options.value,d;d=this.vZ;(b||c!==d)&&this.Tma(c)},j_:function(a,b){-1!==Object.keys(this.Bn).indexOf(a)&&this.widget().toggleClass(this.Bn[a],!!b)},Wx:function(b){if(this.Ev())try{this.H1(this.options.value,
this.Uv.rQ)}catch(c){(b=this.gL(c,b,a.Ic.Sr.sF))&&this.DD("messagesHidden",b)}else a.q.bz>a.q.hn&&a.q.info("Deferred validation skipped as component is readonly or disabled.")},Uka:function(a,b,c,d){var e=a;try{b===this.Uv.PP&&(e=this.MC(a)),this.H1(e,b===this.Uv.rQ)}catch(g){throw a=this.gL(g,c),this.DD("messagesShown",a,d),g;}return e},U_:function(a){var b=!0;this.hC()&&(b=!1);this.UA();b?this.sn()&&this.Wx(a.Ti):this.FD(a)},Tma:function(a,b){var c,d;this.vla(a);c=a;try{c=this.iq(a)}catch(e){d=
this.gL(e),this.DD("messagesShown",d,b)}this.qi(c);c=this.kg();this.q0(c);this.Dn(c,null)},FD:function(a){var b;b=this.US(this.kg(),null,a);void 0===b||!this.isValid()&&this.Bga()||this.F1(b,null,a.Ti)},H1:function(b,c){var d=this.rR(),e,g,f=[];if(this.sn()){e=this.vW();try{e.validate(a.Ea.trim(b))}catch(h){this.$G(h,f)}}if(!c)for(g=0;g<d.length;g++)if(e=d[g],"object"===typeof e)if(e.validate&&"function"===typeof e.validate)try{e.validate(b)}catch(k){this.$G(k,f)}else a.q.bz>a.q.hn&&a.q.info("validator does not support the validate method.");
if(0<f.length)throw d=Error(),d.qx=f,d;}},!0);a.Components.Tm({editableValue:{displayOptions:{messages:["inline"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}}});a.ze={};o_("EditableValueUtils",a.ze,a);a.ze.Doa=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=
void 0!==a.attr("readonly")?!!a.prop("readonly"):void 0;break;case "required":c=a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=void 0!==a.attr("title")?a.prop("title"):void 0;break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.P2=!0,e.value=c):e.P2=!1;return e};a.ze.al=function(b,c,d,e){for(var g={},f=0;f<b.length;f++){var h,k;h=b[f];k=h.W;var l=h.option||k,u=h.ef,w=h.xc,y=d.element,C=d.options[l];void 0===c[l]&&
(C=d.options[l],k=a.ze.Doa(y,k),k.P2?(h=k.value,u&&("boolean"===typeof u?h=a.ze.Ina(l,h):"function"===typeof u&&(h=u.call(d,h))),g[l]=h):void 0===C&&(g[l]=h.$D));u=l in g?g[l]:C;w&&"boolean"===typeof w&&a.ze.kra(l,u)}null!=e&&e(g);d.option(g,{_context:{Hc:!0,Wa:!0}})};a.ze.kra=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+"' has invalid value set: "+b;};a.ze.Ina=
function(a,b){var c=b;switch(a){case "required":c=b?!0:!1}return c};a.Be=function(a){this.Init(a)};a.Ta.OE(a.Ta.gd.lv,a.Be);a.b.ga(a.Be,a.nc,"oj.InlineMessagingStrategy");a.Be.prototype.Er=function(b){a.Be.r.Er.call(this,b);this.b_()};a.Be.prototype.hP=function(a){return a&&void 0!==a.n6?!0:!1};a.Be.prototype.update=function(){a.Be.r.update.call(this);this.b_()};a.Be.prototype.Vk=function(){this.B_();a.Be.r.Vk.call(this)};a.Be.prototype.b_=function(){var a,b;a=this.Zi().widget();this.oV()||(this.Wd=
f("\x3cdiv class\x3d'oj-messaging-inline-container'\x3e\x3c/div\x3e"),this.XG(this.Wd),this.v$(this.Wd),a.append(this.Wd));(b=this.waa())?(a=this.Wd[0],a.innerHTML="",a.innerHTML=b):this.B_()};a.Be.prototype.B_=function(){this.oV()&&this.Wd&&(this.bka(this.Wd),this.cka(this.Wd),this.Wd.remove(),this.Wd=null)};a.Be.prototype.XG=function(b){var c=this.ai();a.l.$c(c,jQuery);a.l.$c(b,jQuery);b=b.uniqueId().attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(b);d=f.trim(d.join(" "));
c.attr("aria-describedby",d)};a.Be.prototype.v$=function(b){a.l.$c(b,jQuery);b.attr("aria-live","polite")};a.Be.prototype.bka=function(b){var c=this.ai();a.l.$c(c,jQuery);a.l.$c(b,jQuery);b=b.attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];b=f.inArray(b,d);-1!==b&&d.splice(b,1);(d=f.trim(d.join(" ")))?c.attr("aria-describedby",d):c.removeAttr("aria-describedby")};a.Be.prototype.cka=function(b){a.l.$c(b,jQuery);b.removeAttr("aria-live")};a.Be.prototype.waa=function(){var a=this.Zi().document[0];
return this.AQ()?this.oH(a):""};a.Be.prototype.oH=function(b){var c;c="";var d=this.oF();this.xF()&&(c=this.pF(),c=a.Oa.a2(b,c,d,!0));return c};a.Be.prototype.oV=function(){return null!=this.Wd};(function(){a.ya("oj._ojLabel",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{ariaRequiredUnsupported:!1,describedById:null,help:{definition:null,source:null},required:!1,rootAttributes:null},va:{NS:"tooltipHelp",OS:"tooltipRequired"},widget:function(){return this.Nr},
refresh:function(){this._super();this.e_();this.a_()},ae:function(a,b){this._super(a,b);this.Uaa();this.IH()},_ComponentCreate:function(){this._super();this.tD=this.eventNamespace+"TouchEatClick";this.kC=this.eventNamespace+"HelpDefPopup";this.In=a.v.Ud();this.Uca()},Qv:function(a){this.Xx=a.attr("class")},Gs:function(){this.Xx?this.element.attr("class",this.Xx):this.element.removeAttr("class")},Uca:function(){var a=this.options,b=a.required,a=a.ariaRequiredUnsupported,c=this.qZ(),d=null;this.Nr=
this.element.wrap(this.bca()).closest(".oj-component");this.Bia();c&&(d=this.YH());this.wU(d);b&&(a?d.appendChild(this.bB()):this.element.before(this.bB()))},wU:function(a){var b=this.options,c=b.help.definition;if(b.help.source||c)this.mha(a),this.E$(),this.haa()},Uaa:function(){var a=this.options.required;if(null!==a&&"boolean"!==typeof a)throw Error("Option 'required' has invalid value set: "+a);},IH:function(){var a=this.options;if(this.qZ()&&null==a.describedById)throw Error("ojLabel's describedById option must be set if help source is set\n\r\n      or (ariaRequiredUnsupported and required is set).");
},Bia:function(){var a=this.element.attr("class"),b;if(a&&(a=a.split(/\s+/),null!=a)){b=a.length;for(var c=0;c<b;c++){var d=a[c];0<d.indexOf("-label")&&(this.Nr.addClass(d),this.element.removeClass(d))}}},YH:function(){var a=this.Nr.find(".oj-label-group"),b=document.createElement("span");b.setAttribute("id",this.options.describedById);a.prepend(b);return b},bca:function(){var a=this.options.rootAttributes,b,c;c="oj-label oj-component";a&&(b=a["class"]);null!==b&&(c=c+" "+b);a=document.createElement("div");
a.className=c;c=document.createElement("div");c.className="oj-label-group";a.appendChild(c);return a},bB:function(){var a=this.A(this.va.OS),b=document.createElement("span");b.className="oj-label-required-icon oj-component-icon";b.setAttribute("role","img");b.setAttribute("title",a);return b},Fba:function(b,c){var d;if(this.GC()){d=document.createElement("a");d.setAttribute("tabindex","0");d.setAttribute("target","_blank");d.className="oj-label-help-icon-anchor oj-label-help-icon oj-component-icon oj-clickable-icon-nocontext";
if(c)try{a.v.jra(c),d.setAttribute("href",c)}catch(e){throw Error(e+". The source option ("+c+") is invalid.");}b?d.setAttribute("title",b):d.setAttribute("title",this.A(this.va.NS))}return d},haa:function(){var a;a=this.options.help.definition;var c,d,e;d=this.widget().find(".oj-label-help-icon-anchor");if(0!=d.length){c=a?a:this.A(this.va.NS);this.$w?(e=f(document.getElementById(this.$w)))&&e.text(c):(a=document.createElement("div"),a.style.display="none",e=f(a),e.uniqueId(),this.$w=e.prop("id"),
e.text(c),c=document.getElementsByTagName("body")[0],c.appendChild(a));this.In&&(this.mB&&this.widget().off(this.tD),this.mB=function(){return!1});var g=this;this.LC||(this.LC=function(a){g.lga(a,e,d,!1)});if(this.In)d.jl({recognizers:[[b.Press,{time:750}]]}).on("press",this.LC);else d.on("focusin"+this.kC+" mousedown"+this.kC,this.LC);a={my:"start bottom",at:"end top",collision:"flipcenter",of:d};e.ojPopup({position:a,modality:"modeless"})}},lga:function(a,b,c,d){if("mousedown"===a.type)d=!0;else if("focusin"===
a.type&&d)d=!1;else{if(this.In)if("press"===a.type){var e=this.widget();e.on("click"+this.tD,this.mB);var g=this;b.on("ojclose",function(){e.off(g.tD);g.mB=null})}else b.off("ojclose");b.ojPopup("isOpen")||b.ojPopup("open",c)}},E$:function(){var a=this.element,b=this.options.help.definition,c;b&&(a.addClass("oj-label-help-def"),(c=a.attr("title"))?a.attr("title",c+" "+b):a.attr("title",b))},y_:function(a){this.In&&(this.widget().off(this.tD),this.mB=null,a.jl().off(this.kC));a.off(this.kC);this.LC=
null},z_:function(){var a;if(null!=this.$w){if(a=f(document.getElementById(this.$w)))a.ojPopup("destroy"),a.remove();this.$w=null}},mka:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},mha:function(a){var b=this.options.help.source,c=this.options.help.definition;this.GC()&&f(a).prepend(this.Fba(c,b))},qZ:function(){var a=this.options;return this.GC()||a.ariaRequiredUnsupported&&a.required},GC:function(){var a=this.options;return a.help.source||a.help.definition},
a_:function(){var a,b;this.IH();this.mka();a=this.Nr.find(".oj-label-help-icon");1===a.length&&(this.y_(a),this.z_(),a.remove());a=this.GC();b=document.getElementById(this.options.describedById);null!=a&&null==b?b=this.YH():null==a&&null!==b&&0===b.children.length&&b.remove();this.wU(b)},e_:function(){var a,b;b=this.Nr.find(".oj-label-required-icon");a=this.options.describedById;this.options.required?(this.IH(),0===b.length?this.options.ariaRequiredUnsupported?(b=document.getElementById(a),null==
b&&(b=this.YH()),b.appendChild(this.bB())):this.element.before(this.bB()):(a=this.A(this.va.OS),b.attr("title",a))):(b.remove(),b=document.getElementById(a),null!==b&&0===b.children.length&&b.remove())},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.e_();"help"===a&&this.a_()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));
return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-label-help-icon")[0]?b={subId:"oj-label-help-icon"}:a===this.widget().find(".oj-label-required-icon")[0]&&(b={subId:"oj-label-required-icon"}));return b||this._superApply(arguments)},_destroy:function(){var b=this.Nr.find(".oj-label-help-icon");this.y_(b);this.z_();a.v.unwrap(this.element,this.Nr);return this._super()}})})();a.ib=function(a){this.Init(a)};a.Ta.OE(a.Ta.gd.Bz,a.ib);a.b.ga(a.ib,a.nc,"oj.PopupMessagingStrategy");
a.ib.qs={ojRadioset:{position:"launcher",Jj:{open:"focus focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",Jj:{open:"focusin mouseover",close:"mouseout"}},ojInputText:{position:"launcher",Jj:{open:"focusin"}},ojTextArea:{position:"launcher",Jj:{open:"focusin"}},ojInputPassword:{position:"launcher",Jj:{open:"focusin"}},ojSwitch:{position:"launcher",Jj:{open:"focusin mouseover",close:"mouseout"}},ojSlider:{position:"launcher",Jj:{open:"focusin mouseover",close:"mouseout"}},"default":{position:"launcher-wrapper",
Jj:{open:"focusin"}}};a.ib.CG="oj-form-control-hint";a.ib.J9="oj-form-control-hint-converter";a.ib.L9="oj-form-control-hint-validator";a.ib.K9="oj-form-control-hint-title";a.ib.prototype.Go=function(b){a.ib.r.Go.call(this,b);this.Zga()};a.ib.prototype.Er=function(b){a.ib.r.Er.call(this,b);this.D1()};a.ib.prototype.update=function(){a.ib.r.update.call(this);this.D1()};a.ib.prototype.Vk=function(){this.Jma();this.xca();a.ib.r.Vk.call(this)};a.ib.prototype.jU=function(){this.HY()&&this.Wd.ojPopup("close")};
a.ib.prototype.Zga=function(){this.KC||this.Yja()};a.ib.prototype.AZ=function(){var b,c;if(this.Naa()&&(c=this.ET(),!a.Ea.Ni(c))){var d=this.PW();b=d.ojPopup("isOpen");b?b&&(b=d[0],b.innerHTML="",b.innerHTML=c,d.ojPopup("refresh")):(b=d[0],b.innerHTML="",b.innerHTML=c,d.ojPopup("open",this.ai()))}};a.ib.prototype.Naa=function(){var a=this.Zi().options,b=a.readOnly||!1;return!(a.disabled||b)};a.ib.prototype.D1=function(){var a;a=!1;var b,c;if(this.HY()){var d=this.PW();a=d.ojPopup("isOpen");b=this.ET();
c=document.activeElement===this.ai()[0]?!0:!1;a?b?(a=d[0],a.innerHTML="",a.innerHTML=b,d.ojPopup("refresh")):d.ojPopup("close"):c&&b&&this.AZ()}};a.ib.prototype.Jma=function(){var b=a.ib.qs[this.Zi().widgetName],b=b?b.Jj:a.ib.qs["default"].Jj;if(b.open){var c=this.KC;delete this.KC;c&&this.ai().off(b.open,c)}b.close&&(c=this.kU)&&this.ai().off(b.close,c)};a.ib.prototype.Yja=function(){var b=this.ai(),c=a.ib.qs[this.Zi().widgetName],c=c?c.Jj:a.ib.qs["default"].Jj;if(c.open){var d=this.KC;d||(d=this.KC=
f.proxy(this.AZ,this));b.on(c.open,d)}c.close&&(d=this.kU,d||(d=this.kU=f.proxy(this.jU,this)),b.on(c.close,d))};a.ib.prototype.Nea=function(){var b,c=a.ib.qs[this.Zi().widgetName];(c=c?c.position:a.ib.qs["default"].position)&&("launcher"===c?b=this.ai():"launcher-wrapper"===c&&(b=this.ai().parent()));b||(b=this.Zi().widget());return{my:"start bottom",at:"end top",collision:"flipcenter",of:b}};a.ib.prototype.PW=function(){if(this.Wd)return this.Wd;var b=a.vd.r3(),c=this.Nea();b.ojPopup("option","position",
c);b.ojPopup("option","close",f.proxy(this.eja,this));b.ojPopup("option","open",f.proxy(this.fja,this));return this.Wd=b};a.ib.prototype.fja=function(b){var c=f(b.target),d=this;window.setTimeout(function(){a.Components.gO(c)?c.ojPopup("option","autoDismiss","focusLoss"):delete d.Wd},10)};a.ib.prototype.eja=function(b){b=f(b.target);a.Components.gO(b)&&(b.ojPopup("option","autoDismiss","none"),b.ojPopup("option","open",null),b.ojPopup("option","close",null));delete this.Wd;b.children().remove()};
a.ib.prototype.xca=function(){this.jU();a.vd.koa()};a.ib.prototype.ET=function(){var b="",c=this.Zi().document[0],d=[],e=!1;this.AQ()&&d.push(this.oH(c));(this.JF()||this.CQ()||this.BQ())&&d.push(this.vaa(c));f.each(d,function(d,g){g&&(e?b=b.concat(a.Oa.Noa(c)):e=!0,b=b.concat(g))});return b};a.ib.prototype.oH=function(b){var c;c="";var d=this.oF();this.xF()&&(c=this.pF(),c=a.Oa.a2(b,c,d,!1));return c};a.ib.prototype.vaa=function(b){var c=[],d,e="";this.JF()&&(c=this.WP(),c=c.length?c[0]:"",e+=a.Oa.dN(b,
a.ib.J9,c,!1,a.ib.CG));if(this.CQ())for(c=this.P6(),d=0;d<c.length;d++)e+=a.Oa.dN(b,a.ib.L9,c[d],!1,a.ib.CG);this.BQ()&&(e+=a.Oa.dN(b,a.ib.K9,this.O6(),!0,a.ib.CG));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};a.ib.prototype.HY=function(){return this.Wd?a.Components.gO(this.Wd):!1};a.Oa={};a.Oa.dN=function(b,c,d,e,g){var h;d&&(h=f(b.createElement("div")),h.addClass(g+(" "+c)),h.append(a.Oa.jX(b,d,e)));return h?h.get(0).outerHTML:""};a.Oa.A3=function(b){var c;switch(b){case a.X.Tb.FATAL:c=
a.ha.A("oj-message.fatal");break;case a.X.Tb.ERROR:c=a.ha.A("oj-message.error");break;case a.X.Tb.WARNING:c=a.ha.A("oj-message.warning");break;case a.X.Tb.INFO:c=a.ha.A("oj-message.info");break;case a.X.Tb.CONFIRMATION:c=a.ha.A("oj-message.confirmation")}return c};a.Oa.Noa=function(a){return(a=f(a.createElement("hr")))?a.get(0).outerHTML:""};a.Oa.a2=function(b,c,d,e){var g="",f,h,k,l,u={};l=[];for(f=0;f<c.length;f++)k=c[f],l=k instanceof a.X?k:new a.X(k.summary,k.detail,k.severity),h=a.X.Ju(l.severity),
u[h]||(u[h]=[]),u[h].push(l);for(f=d;f>=a.X.Tb.CONFIRMATION;f--)for(l=u[f]||[],c=0;c<l.length;c++)k=l[c],a.l.$c(k,a.X),h=a.X.Ju(k.severity),d=a.Oa.A3(h),d=k.summary||d,k=k.detail||"",g=g.concat(a.Oa.Z1(b,d,k,h,e));return g};a.Oa.Z1=function(b,c,d,e,g){var h,k;k=a.Oa.A3(e);h=f(b.createElement("div"));h.addClass(a.Oa.M9);g&&h.addClass(a.Oa.Vea(e));g=f(b.createElement("span"));g.addClass(a.Oa.Uea(e)).attr("title",k).attr("role","img");h.append(g);e=f(b.createElement("span"));e.addClass(a.Oa.P9);k=f(b.createElement("div"));
k.addClass(a.Oa.T9).text(c);e.append(k);d&&(c=a.Oa.jX(b,d,!0),b=f(b.createElement("div")),b.addClass(a.Oa.Q9).append(c),e.append(b));h.append(e);return h?h.get(0).outerHTML:""};a.Oa.Uea=function(b){var c;switch(b){case a.X.Tb.FATAL:c=a.Oa.rS;break;case a.X.Tb.ERROR:c=a.Oa.rS;break;case a.X.Tb.WARNING:c=a.Oa.V9;break;case a.X.Tb.INFO:c=a.Oa.S9;break;case a.X.Tb.CONFIRMATION:c=a.Oa.O9}return a.Oa.O7+c};a.Oa.Vea=function(b){switch(b){case a.X.Tb.FATAL:b=a.Oa.qS;break;case a.X.Tb.ERROR:b=a.Oa.qS;break;
case a.X.Tb.WARNING:b=a.Oa.U9;break;case a.X.Tb.INFO:b=a.Oa.R9;break;default:b=a.Oa.N9}return b};a.Oa.jX=function(b,c,d){var e=null;a.Ea.qd(c)&&(d&&a.v.Gpa(c)?e=a.v.Fna(c.substring(6,c.length-7)):(e=b.createElement("span"),e.textContent=c));return e};a.Oa.O7="oj-component-icon oj-message-status-icon ";a.Oa.M9="oj-message";a.Oa.T9="oj-message-summary";a.Oa.Q9="oj-message-detail";a.Oa.P9="oj-message-content";a.Oa.rS="oj-message-error-icon";a.Oa.V9="oj-message-warning-icon";a.Oa.S9="oj-message-info-icon";
a.Oa.O9="oj-message-confirmation-icon";a.Oa.qS="oj-message-error";a.Oa.U9="oj-message-warning";a.Oa.R9="oj-message-info";a.Oa.N9="oj-message-confirmation";a.vd={};a.vd.r3=function(){var b=a.vd.OW(),c=b.find("."+a.vd.DG);0===c.length?(c=f(a.vd.Mea()).hide(),c.appendTo(b),c.ojPopup({rootAttributes:{"class":a.vd.W9},initialFocus:"none",tail:"simple",autoDismiss:"none",modality:"modeless"})):c=f(c[0]);return c};a.vd.koa=function(){if(0<a.vd.fea()){var b=a.vd.r3();b.ojPopup("destroy");b.remove()}};a.vd.OW=
function(){var b=f("#"+a.vd.OR);if(0<b.length)return b;b=f("\x3cdiv\x3e");b.attr("id",a.vd.OR);b.attr("role","presentation");b.appendTo(f(document.body));return b};a.vd.fea=function(){return a.vd.OW().find("."+a.vd.DG).length};a.vd.Mea=function(){return"\x3cdiv class\x3d'"+a.vd.DG+"'\x3e\x3c/div\x3e"};a.vd.DG="oj-messaging-popup-container";a.vd.W9="oj-messaging-popup";a.vd.OR="__oj_messaging_popup_pool"});