/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","knockout","jqueryui-amd/widget"],function(a,f,b){function d(){this.Init()}function c(b,a){var c={};c.value=a.value;return c}function e(b,a){var c={},d=a.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[a.option]=a.value);return c}function g(b,a,c){"pieCenter"===b&&a.template&&(a.renderer=w(c,a.template));return{pieCenter:a}}function h(a,c){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(b){b.$optionContext=d});b.renderTemplate(c,
g,null,e);return null}}function k(b,a,c){return"optionTemplate"===b&&null!==a?{optionRenderer:h(c,String(a))}:null}function l(b,a){this.Init(b,a)}function m(b,c,d,e,g){b=r(b,c,d,e);d=b.zna;if(null==d)return g;var f={};s(d,function(b,a){f[b]=a});g=a.zc.Lf({},g);g[c]=n(e,f,b.Bna);return g}function n(b,c,d){function e(){var d={};Object.keys(c).forEach(function(e){var g=a.ia.wA(c[e]).bind(null,b);Object.defineProperty(d,e,{get:g,enumerable:!0})});Object.defineProperty(d,a.ia.$R,{value:c});return d}e.toString=
function(){return d};return e}function p(b,a,c){var d=a.getBindingsString;if(d)return d.call(a,b,c);switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return(b=b.nodeValue.match(/^\s*ko(?:\s+([\s\S]+))?\s*$/))?b[1]:null}return null}function r(a,c,d,e){var g=null;a=p(a,d,e);a=b.jsonExpressionRewriting.parseObjectLiteral(a);var f=null;s(a,function(b,a){return b===c?(f=a,!0):!1});null!=f&&0===f.indexOf("{")&&(g=b.jsonExpressionRewriting.parseObjectLiteral(f));return{zna:g,Bna:f}}function s(b,
a){for(var c=0;c<b.length;c++){var d=b[c],e=d.key,d=d.value;if(null!=e&&null!=d&&a(e.trim(),d.trim()))break}}function q(a,c){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(b){b.$key=d.key;b.$metadata=d.metadata;b.$headerContext=d});b.renderTemplate(c,g,{afterRender:function(b){f(b)._ojDetectCleanData()}},e);return null}}function t(a,c){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(b){b.$keys=d.keys;b.$metadata=d.metadata;
b.$cellContext=d});b.renderTemplate(c,g,{afterRender:function(b){f(b)._ojDetectCleanData()}},e);return null}}function v(a,c){return function(d){var e=a.createChildContext(d.data);b.renderTemplate(c,e,{afterRender:function(b){f(b)._ojDetectCleanData()}},d.parentElement);return null}}function x(a,c){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(b){b.$itemContext=d});b.renderTemplate(c,g,{afterRender:function(b){f(b)._ojDetectCleanData()}},e,"replaceNode");
return null}}function u(b,a,c){return"item"==b?(b=a.template,null!=b&&(a.renderer=x(c,b)),{item:a}):null}function w(a,c){return function(d){var e=document.createElement("div");e.style.display="none";d=a.createChildContext(d);b.renderTemplate(c,d,{afterRender:function(b){f(b)._ojDetectCleanData()}},e);return(d=e.children[0])?(e.removeChild(d),f(e).remove(),d):null}}function y(b,a,c){"center"===b&&a.template&&(a.renderer=w(c,a.template));return{center:a}}function C(a,c,d){var e={};(function(c,d){e=
function(e){var g=null,h=null;"header"==d?(g=a.createChildContext(null,null,function(b){b.$columnIndex=e.columnIndex;b.$headerContext=e.headerContext;b.$data=e.data}),h=e.headerContext.parentElement):"cell"==d&&(g=a.createChildContext(e.row,null,function(b){b.$columnIndex=e.columnIndex;b.$cellContext=e.cellContext}),h=e.cellContext.parentElement);"footer"==d&&(g=a.createChildContext(null,null,function(b){b.$columnIndex=e.columnIndex;b.$footerContext=e.footerContext}),h=e.footerContext.parentElement);
b.renderTemplate(c,g,{afterRender:function(b){f(b)._ojDetectCleanData()}},h,"replaceNode")}})(d,c);return e}function J(a,c){return function(d){var e=a.createChildContext(d.row,null,function(b){b.$rowContext=d.rowContext});b.renderTemplate(c,e,{afterRender:function(b){f(b)._ojDetectCleanData()}},d.rowContext.parentElement,"replaceNode")}}function H(a,c){return function(d){var e=a.createChildContext(d.data);b.renderTemplate(c,e,{afterRender:function(b){f(b)._ojDetectCleanData()}},d.parentElement);return null}}
function F(b,a,c){if("areaLayers"===b){for(b=0;b<a.length;b++){var d=a[b].areaDataLayer;if(d){var e=d.template;null!=e&&(d._templateRenderer=H(c,e))}}return{areaLayers:a}}if("pointDataLayers"===b){for(b=0;b<a.length;b++)e=a[b].template,null!=e&&(a[b]._templateRenderer=H(c,e));return{pointDataLayers:a}}return null}function G(a,c){return function(d){var e=document.createElement("div");e.style.display="none";d=a.createChildContext(d);b.renderTemplate(c,d,{afterRender:function(b){f(b)._ojDetectCleanData()}},
e);return(d=e.children[0])?(e.removeChild(d),f(e).remove(),d):null}}function E(b,a,c){"tooltip"===b&&a.template&&(a.renderer=G(c,a.template));return{tooltip:a}}a.b.ga(d,a.b,"ComponentBinding.GlobalChangeQueue");d.prototype.Init=function(){d.r.Init.call(this);this.xD=[];this.Hx=[]};d.prototype.oqa=function(b){-1===this.xD.indexOf(b)&&(this.xD.push(b),this.eB||(this.eB=setTimeout(a.b.r2(this,this.YU),1)))};d.prototype.qN=function(){this.eB&&clearTimeout(this.eB);this.YU()};d.prototype.YU=function(){var b;
this.eB=null;var a=this.xD;this.xD=[];for(b=0;b<a.length;b++){var c=a[b];this.Hx.push({sP:c,Jo:c.yoa()})}for(;0<this.Hx.length;)b=this.Hx.shift(),b.sP.pna(b.Jo)};a.ia=function(b,a){this.Init(b,a)};o_("ComponentBinding",a.ia,a);a.b.ga(a.ia,a.b,"oj.ComponentBinding");a.ia.create=function(c,d){if(null==c)throw"Binding name is required!";var e=new a.ia(c,d),g=b.bindingHandlers,f,h=Array.isArray(c)?c:[c];for(f=0;f<h.length;f++){var q=h[f];a.ia.oS.push(q);g[q]=e}return e};o_("ComponentBinding.create",a.ia.create,
a);a.ia.Me=function(){return a.ia.z8};o_("ComponentBinding.getDefaultInstance",a.ia.Me,a);a.ia.prototype.Oe=function(b){var a=b["for"],a=null==a?"@global":a,c=this.DC[a]||[];c.push(b);this.DC[a]=c};a.b.g("ComponentBinding.prototype.setupManagedAttributes",{Oe:a.ia.prototype.Oe});a.ia.qN=function(){a.ia.ST.qN()};o_("ComponentBinding.deliverChanges",a.ia.qN,a);a.ia.prototype.Init=function(b,c){a.ia.r.Init.call(this);"string"===typeof c&&(c={componentName:c});this.kH=c||{};Array.isArray(b);this.init=
this._init.bind(this);this.update=this.Bo.bind(this);this.DC={}};a.ia.prototype._init=function(a,c,d,e,g){b.applyBindingsToDescendants(g,a);return{controlsDescendantBindings:!0}};a.ia.prototype.Bo=function(c,d,e,g,h){function q(b){p.forEach(function(b){b.dispose()});p=[];b&&t&&(t("destroy"),t=null);r&&(r.Du(),r=null);n.off(a.ia.uR)}function k(b,d,g){if(null!=b){var f=n[b];if("function"!==typeof f)a.q.error("Component %s is not found",b);else{f=f.bind(n);r=new l(f,a.ia.ST);var q=Object.keys(g).filter(function(b){return!(null==
b||b===d)});t=this.Qga(c,{O:f,xy:r,m2:b,oz:q,Lna:p,mp:function(){return g},vu:e,er:h,joa:function(){t=null}})}}}var p=[],m=0,t,r,n=f(c);b.ignoreDependencies(function(){b.computed(function(){var c=b.utils.unwrapObservable(d());"object"!==typeof c&&a.q.error("ojComponent binding should evaluate to an object");var e=this.kH.componentName,g,f=!1;if(null==e&null!=c){for(var h=[a.ia.J7,"role"],p=0;!f&&p<h.length;p++)g=h[p],g in c&&(f=!0,e=c[g]);f||a.q.error("component attribute is required for the ojComponent binding");
e=b.utils.unwrapObservable(e)}0==m?m=1:b.ignoreDependencies(q,this,[!0]);b.ignoreDependencies(k,this,[e,g,c])},this,{disposeWhenNodeIsRemoved:c})},this);b.utils.domNodeDisposal.addDisposeCallback(c,q.bind(this,!1))};a.ia.prototype.Qga=function(c,d){function e(){var b=this.xja,g=a.ia.yma(d.mp()[b]);if(0===q){var f=r[b];null!=f?(k[b]=f,f=f.Em,null!=f&&(b=f(b,g,c,m,d.mp,d.vu,d.er)||{},a.zc.Lf(s,b))):s[b]=g}else if(!h)if(null!=r[b]){if(f=r[b].update,null!=f)for(b=f(b,g,c,m,d.mp,d.vu,d.er)||{},g=Object.keys(b),
f=0;f<g.length;f++){var p=g[f];d.xy.M1(p,b[p])}}else d.xy.M1(b,g)}function g(b){b.target&&b.target==c&&(d.joa(),(b=t.kH.beforeDestroy)&&b(c,m,d.mp,d.vu,d.er),a.ia.ZU(!1,k,c,m,d.mp,d.vu,d.er),h=!0,d.xy.Du(),c.removeEventListener("_ojDestroy",g))}var h=!1,q=0,k={},p=f(c),m=d.O,l=d.m2,t=this;c.addEventListener("_ojDestroy",g);var r=a.ia.P_(this.DC,d.oz,l),n=a.ia.Me();this!==n&&(l=n.uea(d.oz,l),a.zc.Lf(l,r),r=l);for(var s={},l=0;l<d.oz.length;l++)d.Lna.push(b.computed(e,{xja:d.oz[l]}));q=1;a.ia.$ja(p,
d);p=a.ia.zV(s);l=Object.keys(p);l.forEach(function(b){delete s[b]});m(s);for(n=0;n<l.length;n++){var v=l[n];m("option",v,p[v])}(p=this.kH.afterCreate)&&p(c,m,d.mp,d.vu,d.er);a.ia.ZU(!0,k,c,m,d.mp,d.vu,d.er);s=null;return m};a.ia.wA=function(b){return new Function("$context","with($context){with($data||{}){return "+b+";}}")};a.ia.prototype.uea=function(b,c){return a.ia.P_(this.DC,b,c)};a.ia.P_=function(b,a,c){function d(a,c){var e=b[a];if(null!=e)for(var f=e.length-1;0<=f;f--){var h=e[f];null!=h.attributes&&
g.push(h);if(c&&(h=h.use,null!=h))for(var h=Array.isArray(h)?h:[h],q=0;q<h.length;q++)d(h[q],!0)}}var e={},g=[];d(c,!0);c=f.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);d("@global",!1);if(0<g.length)for(c=0;c<a.length;c++)for(var h=a[c],q=0;q<g.length;q++){var k=g[q];if(0<=k.attributes.indexOf(h)){e[h]={Em:k.init,update:k.update,tu:k.afterCreate,Ana:k.beforeDestroy};break}}return e};a.ia.uR=".oj_ko";a.ia.$ja=function(b,
d){for(var g={"^slider$":[{event:"slidechange",getter:c}],"^oj*":[{event:"ojoptionchange",getter:e}]},f={},h=Object.keys(g),q=0;q<h.length;q++){var k=h[q];if(d.m2.match(k)){g=g[k];for(h=0;h<g.length;h++)q=g[h],b.on(q.event+a.ia.uR,{Voa:q.getter},function(b,c){b.stopPropagation();var e=b.data.Voa(b,c),g=d.mp(),h;for(h in e){d.xy.Sqa(h);try{if(0<=d.oz.indexOf(h)){var q=g[a.ia.$R];a.ia.hna(h,g[h],e[h],null==q?null:q[h],d.er,f)}}finally{d.xy.xqa(h)}}});break}}};a.ia.hna=function(c,d,e,g,f,h){null!=d&&
b.isObservable(d)?b.isWriteableObservable(d)&&d(e):(c in h||(d=null,g=a.Vr.t3(g),null!=g&&(d=a.ia.wA(g)),h[c]=d),(c=h[c])&&c(f)(e))};a.ia.yma=function(c){c=b.utils.unwrapObservable(c);(Array.isArray(c)||a.zc.isPlainObject(c))&&c.ojConvertToJS&&(c=b.toJS(c));return c};a.ia.zV=function(b){for(var a={},c=Object.keys(b),d=0;d<c.length;d++){var e=c[d];0<=e.indexOf(".")&&(a[e]=b[e])}return a};a.ia.ZU=function(b,a,c,d,e,g,f){for(var h=Object.keys(a),q=0;q<h.length;q++){var k=h[q],p=a[k];(p=b?p.tu:p.Ana)&&
p(k,c,d,e,g,f)}};a.ia.ST=new d;a.ia.s$=function(){return a.Ns()&&b?b.version:""};a.ia.Eha=function(b){return 0<=a.ia.oS.indexOf(b)};a.ia.oS=[];a.ia.J7="component";a.ia.$R="_ojOptions";(function(){var c=b.removeNode;b.removeNode=function(b){var d=a.Components;d&&a.v.A5(b);try{c(b)}finally{d&&a.v.A5(null)}}})();a.ia.z8=a.ia.create(["ojComponent","jqueryUI"]);f.widget("oj._ojDetectCleanData",{_destroy:function(){var a,c;a=b.utils.domNodeDisposal;c=a.cleanExternalData;a.cleanExternalData=function(){};
try{b.cleanNode(this.element[0])}finally{a.cleanExternalData=c}}});a.ia.Me().Oe({attributes:["pieCenter"],init:function(b,a,c,d,e,f,h){return g(b,a,h)},update:function(b,a,c,d,e,f,h){return g(b,a,h)},"for":"ojChart"});a.ia.Me().Oe({attributes:["optionTemplate"],init:function(b,a,c,d,e,g,f){b=k(b,a,f);if(null!==b)return b},update:function(b,a,c,d,e,g,f){return k(b,a,f)},"for":"ComboboxOptionRenderer"});a.ia.Me().Oe({"for":"ojCombobox",use:"ComboboxOptionRenderer"});a.ia.Me().Oe({"for":"ojSelect",use:"ComboboxOptionRenderer"});
a.ia.Me().Oe({"for":"ojInputSearch",use:"ComboboxOptionRenderer"});a.b.ga(l,a.b,"ComponentBinding.ComponentChangeTracker");l.prototype.Init=function(b,a){l.r.Init.call(this);this.ka=b;this.Hx=a;this.GH={};this.iu={}};l.prototype.M1=function(b,a){this.Iha(b)||this.jV||(this.GH[b]=a,this.Hx.oqa(this))};l.prototype.Du=function(){this.jV=!0};l.prototype.xqa=function(b){var c=this.iu[b]||0;a.l.assert(0<c,"ComponentChangeTracker suspendCount underflow");c--;0==c?delete this.iu[b]:this.iu[b]=c};l.prototype.Sqa=
function(b){this.iu[b]=(this.iu[b]||0)+1};l.prototype.pna=function(b){if(!this.jV){var c=a.ia.zV(b),d={changed:!0};this.ka("option",b,d);for(var e in c)this.ka("option",e,c[e],d)}};l.prototype.yoa=function(){var b=this.GH;this.GH={};return b};l.prototype.Iha=function(b){return 1<=(this.iu[b]||0)};b.bindingHandlers.ojContextMenu={update:function(c,d){function e(b,a,c){r=c;var d=q();if(r)p.one("touchend.ojContextMenu",function(){d.Ls(!0);setTimeout(function(){d.Ls(!1)},50)});"touchstart"===v&&"contextmenu"===
b.type||"contextmenu"===v&&"touchstart"===b.type?(v=null,clearTimeout(s)):!b.isDefaultPrevented()&&(a={launcher:p,initialFocus:"menu",position:{mouse:{my:"start top",at:"start bottom",of:b},touch:{my:"start\x3e40 center",at:"start bottom",of:b,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher"}}[a]},d.xA=!0,d.open(b,a),d.xA=!1,h().is(":visible")&&(b.preventDefault(),document.addEventListener("keyup",g),"touchstart"===b.type||"contextmenu"===b.type))&&(v=b.type,s=setTimeout(function(){v=
null},300))}function g(b){121==b.which&&b.shiftKey&&h().is(":visible")&&b.preventDefault()}function h(){m||k();return m}function q(){l||k();return l}function k(){m=f(u).first();l=m.data("oj-ojMenu");if(!l)throw Error('"contextMenu" set to "'+u+'", which does not reference a valid JET Menu.');m.on("ojclose.ojContextMenu",function(){document.removeEventListener("keyup",g)})}var p=f(c),m,l,t,r=!1,n=!1,s,v=null,x;p.off(".ojContextMenu").removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",
x,!0);m&&m.off(".ojContextMenu");clearTimeout(t);m=l=void 0;var u=b.utils.unwrapObservable(d());"string"!==f.type(u)&&(u=c.getAttribute("contextmenu"))&&(u="#"+u);x=function(b){if(r)return b.preventDefault(),b.stopPropagation(),r=!1};c.addEventListener("click",x,!0);p.on("touchstart.ojContextMenu mousedown.ojContextMenu keydown.ojContextMenu ",function(b){if("mousedown"!==b.type||!q().Ls())return r=!1,"touchstart"===b.type&&(n=!0,t=setTimeout(e.bind(void 0,b,"touch",!0),750)),!0}).on("touchend.ojContextMenu touchcancel.ojContextMenu",
function(){n=!1;clearTimeout(t);return!0}).on("keydown.ojContextMenu contextmenu.ojContextMenu",function(b){("contextmenu"===b.type||121==b.which&&b.shiftKey)&&e(b,n?"touch":"keydown"===b.type?"keyboard":"mouse",!1);return!0}).addClass(a.v.Ud()?"oj-menu-context-menu-launcher":"")}};a.VS=(new function(){function c(b,a,e){var g=b[e];a[e]=function(){var a=g?g.apply(b,arguments):null,c=d[e];if(null!=c){var f=arguments;c.forEach(function(c){var d=Array.prototype.slice.call(f);d.push(a,b);a=c.apply(null,
d)})}return a}}this.dO=function(){var d=b.bindingProvider,e=d.instance;if(!e.getBindingAccessors)return a.q.error("JET's Knockout bindings are not compatible with the current binding provider since it does not implement getBindingAccessors()"),this;var g=d.instance={},d=[];d.push("getBindingAccessors","nodeHasBindings","getBindings","preprocessNode");d.forEach(function(b){c(e,g,b)});return this};this.N1=function(b){Object.keys(b).forEach(function(a){d[a]=d[a]||[];d[a].push(b[a])})};var d={}}).dO();
a.VS.N1({getBindingAccessors:function(b,c,d,e){if(null==d)return null;var g;a:{g=Object.keys(d);for(var f=-0;f<g.length;f++){var h=g[f];if(a.ia.Eha(h)){g=h;break a}}g=null}null!=g&&(d=m(b,g,e,c,d));return d}});a.ia.Me().Oe({attributes:["header","cell"],init:function(b,a,c,d,e,g,f){if("header"===b)return b=a.row,null!=b&&(c=b.template,null!=c&&(b.renderer=q(f,c))),b=a.column,null!=b&&(c=b.template,null!=c&&(b.renderer=q(f,c))),{header:a};if("cell"===b)return b=a.template,null!=b&&(a.renderer=t(f,b)),
{cell:a}},update:function(b,a,c,d,e,g,f){return"header"===b?(b=a.row,null!=b&&(c=b.template,null!=c&&(b.renderer=q(f,c))),b=a.column,null!=b&&(c=b.template,null!=c&&(b.renderer=q(f,c))),{header:a}):"cell"===b?(b=a.template,null!=b&&(a.renderer=t(f,b)),{cell:a}):null},"for":"ojDataGrid"});a.ia.Me().Oe({attributes:["template"],init:function(b,a,c,d,e,g,f){return"template"===b?{_templateFunction:v(f,a)}:null},update:function(b,a,c,d,e,g,f){return"template"===b?{_templateFunction:v(f,a)}:null},"for":"ojDiagram"});
(function(){a.Vr={};a.Vr.h3=function(a){var d={};if(a){var e=b.exec(a),e=e?e[1]:null;e||(d.noa=!0,e=(e=c.exec(a))?e[1]:null);d.expr=e}return d};a.Vr.t3=function(b){var a=["true","false","null","undefined"];if(null==b||0<=a.indexOf(b))return null;a=b.match(d);return null===a?null:"function(v){"+(a[1]?"Object("+a[1]+")"+a[2]:b)+"\x3dv;}"};var b=/(?:\{\{\s*)([^\s]+)(?:\s*\}\})/,c=/(?:\[\[\s*)([^\s]+)(?:\s*\]\])/,d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i})();a.oO={};o_("koStringTemplateEngine",
a.oO,a);a.oO.dO=function(){if(!b.templates){var a={},c={},d=new b.nativeTemplateEngine,e=function(b){this.lu=b;this.text=function(b){if(!b)return a[this.lu];a[this.lu]=b};this.data=function(b,a){c[this.lu]||(c[this.lu]={});if(1===arguments.length)return c[this.lu][b];c[this.lu][b]=a}};d.makeTemplateSource=function(a,c){if("string"==typeof a){c=c||document;var d=c.getElementById(a);return d?new b.templateSources.domElement(d):new e(a)}if(a&&1==a.nodeType||8==a.nodeType)return new b.templateSources.anonymousTemplate(a)};
b.templates=a;b.setTemplateEngine(d)}};o_("koStringTemplateEngine.install",a.oO.dO,a);a.ia.Me().Oe({attributes:["item"],init:function(b,a,c,d,e,g,f){b=u(b,a,f);if(null!=b)return b},update:function(b,a,c,d,e,g,f){return u(b,a,f)},"for":"ojListViewRenderer"});a.ia.Me().Oe({"for":"ojListView",use:"ojListViewRenderer"});a.ia.Me().Oe({"for":"ojNavigationList",use:"ojListViewRenderer"});a.ResponsiveKnockoutUtils={};a.ResponsiveKnockoutUtils.createMediaQueryObservable=function(a){if(null==a)throw Error("oj.ResponsiveKnockoutUtils.createMediaQueryObservable: aborting, queryString is null");
a=window.matchMedia(a);var c=b.observable(a.matches);a.addListener(function(b){c(b.matches)});-1!=navigator.userAgent.indexOf("WebKit")&&-1==navigator.userAgent.indexOf("Chrome")&&f(window).resize(function(){0===f("body").has(".oj-webkit-bug-123293").length&&f("body").append('\x3cdiv aria-hidden\x3d"true" class\x3d"oj-helper-hidden-accessible oj-webkit-bug-123293"\x3e');f(".oj-webkit-bug-123293").text((new Date).getMilliseconds().toString())});return c};a.ResponsiveKnockoutUtils.createScreenRangeObservable=
function(){var c=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.XXL_UP),d=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.XL_UP),e=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.LG_UP),g=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.MD_UP),f=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.SM_UP),h=null==c?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(c),
q=null==d?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(d),k=null==e?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(e),p=null==g?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(g),m=null==f?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(f);return b.computed(function(){if(h&&h())return a.ResponsiveUtils.SCREEN_RANGE.XXL;if(q&&q())return a.ResponsiveUtils.SCREEN_RANGE.XL;if(k&&k())return a.ResponsiveUtils.SCREEN_RANGE.LG;if(p&&p())return a.ResponsiveUtils.SCREEN_RANGE.MD;
if(m&&m())return a.ResponsiveUtils.SCREEN_RANGE.SM;throw Error(" NO MATCH in oj.ResponsiveKnockoutUtils.createScreenRangeObservable");})};a.ia.Me().Oe({attributes:["center"],init:function(b,a,c,d,e,g,f){return y(b,a,f)},update:function(b,a,c,d,e,g,f){return y(b,a,f)},"for":"ojStatusMeterGauge"});a.ia.Me().Oe({attributes:["columns","columnsDefault","rowTemplate"],init:function(b,a,c,d,e,g,f){if("columns"==b||"columnsDefault"==b){for(c=0;c<a.length;c++){var h=a[c];d=h.template;e=h.footerTemplate;g=
h.headerTemplate;null!=d&&(h.renderer=C(f,"cell",d));null!=e&&(h.footerRenderer=C(f,"footer",e));null!=g&&(h.headerRenderer=C(f,"header",g))}return"columns"==b?{columns:a}:{columnsDefault:a}}if("rowTemplate"==b)return{rowRenderer:J(f,a)}},update:function(b,a,c,d,e,g,f){if("columns"==b||"columnsDefault"==b){var h;for(c=0;c<a.length;c++){var q=a[c];e=q.template;g=q.footerTemplate;h=q.headerTemplate;null!=e&&(q.renderer=C(f,"cell",e));null!=g&&(q.footerRenderer=C(f,"footer",g));null!=h&&(q.headerRenderer=
C(f,"header",h))}"columns"==b?d({columns:a}):d({columnsDefault:a})}else if("rowTemplate"==b)return{rowRenderer:J(f,a)};return null},"for":"ojTable"});a.ia.Me().Oe({attributes:["areaLayers","pointDataLayers"],init:function(b,a,c,d,e,g,f){return F(b,a,f)},update:function(b,a,c,d,e,g,f){return F(b,a,f)},"for":"ojThematicMap"});a.ia.Me().Oe({attributes:["tooltip"],init:function(b,a,c,d,e,g,f){return E(b,a,f)},update:function(b,a,c,d,e,g,f){return E(b,a,f)},"for":"tooltipOptionRenderer"});(function(){for(var b=
"ojChart ojDiagram ojNBox ojPictoChart ojSunburst ojTagCloud ojThematicMap ojTreemap ojDialGauge ojLedGauge ojRatingGauge ojSparkChart ojStatusMeterGauge".split(" "),c=0;c<b.length;c++)a.ia.Me().Oe({"for":b[c],use:"tooltipOptionRenderer"})})()});