/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","promise"],function(a,f){a.$r={};a.$r.hc={viewPath:"text!views/",viewSuffix:".html",modelPath:"viewModels/",initializeMethod:"initialize",disposeMethod:"dispose",activatedHandler:"handleActivated",attachedHandler:"handleAttached",detachedHandler:"handleDetached",bindingsAppliedHandler:"handleBindingsApplied",deactivatedHandler:"handleDeactivated",transitionCompletedHandler:"handleTransitionCompleted"};o_("ModuleBinding.defaults",a.$r.hc,a);(function(){function b(b,
d,e,g,h,k,l){var n=d.canAnimate;if(null==n||n.call(d,b)){var p,r;if(n=d.prepareAnimation.call(d,b))p=n.newViewParent,r=n.oldViewParent;var s=p||e;r&&r!==e?c(g,r):s===e&&k(null);s!==e&&f.virtualElements.setDomNodeChildren(s,[]);h(s);var G=Array.prototype.slice.call(s.childNodes),E=!1,B=function(){E||(E=!0,e!==s&&m(e,G))},z=k.bind(null,r);b.newViewParent=p;b.oldViewParent=r;b.oldViewNodes=g;b.removeOldView=z;b.insertNewView=B;var L=function(){z();B();l()};return d.animate.call(d,b).then(L,function(){L();
a.q.error("ojModule animation promise was rejected")})}}function d(a,b,c){b=b||a;var d=[];c&&a===b&&(c.parentNode.removeChild(c),d.push(c));f.virtualElements.setDomNodeChildren(b,d)}function c(a,b){a.forEach(function(a){b.appendChild(a)})}function e(a,b,c){if(a&&a[b]){var d={element:c[0],valueAccessor:c[1]};2<c.length&&(d.viewModel=c[2],3<c.length&&(d["boolean"===typeof c[3]?"fromCache":"cachedNodes"]=c[3]));return f.ignoreDependencies(a[b],a,[d])}}function g(b,c,d){if(null!=b&&(c=a.$r.hc[c],null!=
c&&b&&(c=b[c],"function"===typeof c))){var e=void 0;d&&(e={element:d[0],valueAccessor:d[1]},2<d.length&&(e["boolean"===typeof d[2]?"fromCache":"cachedNodes"]=d[2]));return f.ignoreDependencies(c,b,[e])}}function h(a,b,c){var d=[];for(a=f.virtualElements.firstChild(a);null!=a&&a!=c;a=a.nextSibling)a!=b&&d.push(a);return d}function k(a,b){var c=[],d=f.virtualElements.firstChild(a);l(d,b,function(a){c.push(a)});return c}function l(a,b,c){for(;null!=a;){var d=f.virtualElements.nextSibling(a),e=a.nodeType;
a===b||1!==e&&8!==e||c(a);a=d}}function m(a,b){for(var c=b.length-1;0<=c;c--)f.virtualElements.prepend(a,b[c])}function n(b,c){if(null!=a.Components)for(var d=0;d<b.length;d++)c?a.Components.Vm(b[d]):a.Components.jp(b[d])}function p(a){if("string"===typeof a)a=f.utils.parseHtmlFragment(a);else if(window.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType)a=f.utils.arrayPushAll([],a.childNodes);else if(Array.isArray(a))a=f.utils.arrayPushAll([],a);else throw"The View ("+a+") has an unsupported type";
return a}function r(a){return new Promise(function(b){require([a],function(a){b(a)},function(){throw Error("ojModule failed to load "+a);})})}function s(a){return a?new Promise(function(b){a.then(b,b)}):a}f.bindingHandlers.ojModule={init:function(q,t,v,x,u){function w(a){if(a!=G)throw Error("Promise cancelled because ojModule is fetching new View and ViewModel");}function y(a){g(a,"disposeMethod",[q,t])}var C,J,H={},F,G=-1,E,B;f.utils.domNodeDisposal.addDisposeCallback(q,function(){y(C);for(var a=
Object.keys(H),b=0;b<a.length;b++)y(H[a[b]].$o)});8===q.nodeType&&(f.virtualElements.setDomNodeChildren(q,[]),B=q.nextSibling);f.computed(function(){G++;var v=0===G,x=f.utils.unwrapObservable,A=x(t()),P,R,K,I,D,N,O,X;"string"===typeof A?P=A:(P=x(A.name),R=x(A.viewName),K=x(A.params),I=x(A.viewModelFactory),D=x(A.createViewFunction),N=x(A.cacheKey),O=x(A.lifecycleListener),X=x(A.animation));var x=e(O,"activated",[q,t]),M,U,Z=null==N?null:H[N];if(null!=Z)delete H[N],M=Promise.resolve(Z.view),U=Promise.resolve(Z.$o);
else if(null!=I&&(U=f.ignoreDependencies(I.createViewModel,I,[K,t])),null==U&&null!=P&&(U=r(a.$r.hc.modelPath+P)),null!=U&&(U=U.then(function(a,b){w(a);return b="function"===typeof b?new b(K):g(b,"initializeMethod",[q,t])||b}.bind(null,G)),null!=D&&(M=U.then(function(a,b){w(a);if(null==b)throw"createViewFunction option cannot be used when the ViewModel is null";var c=b[D];if(null==c)throw"function specified by the createViewFunction option was not found on the ViewModel";return c.call(b)}.bind(null,
G)))),null==M)if(R=null==R?P:R,null!=R)M=r(a.$r.hc.viewPath+R+a.$r.hc.viewSuffix);else throw Error("View name must be specified");if(null==M)throw Error("ojModule is missing a View");var W;null!=U&&(W=U.then(function(a,b){w(a);return g(b,"activatedHandler",[q,t])}.bind(null,G)));Promise.all([M,U,x,W,J]).then(function(a,x){if(a==G){var w=x[0];if(null==w)throw"The module's View was resolved to null";var r=p(w),A=x[1],D=!1,I,L=h(q,E,B),M=k(q,E);null!=F&&(D=!0,I=L,E||(E=document.createElement("div"),
E.className="oj-helper-module-cache",f.virtualElements.prepend(q,E)));var P=!1,w=function(a){P||(P=!0,D?c(L,E):M.forEach(function(a){f.cleanNode(a)}),d(q,a||q,E),v||(e(O,"detached",[q,t,C,I]),g(C,"detachedHandler",[q,t,I]),e(O,"deactivated",[q,t,C]),g(C,"deactivatedHandler",[q,t])),D?(n(I,!1),H[F]={$o:C,view:I}):y(C),C=A,F=N)},R=function(a){a=a||q;m(a,r);var b=null!=Z;b&&n(r,!0);e(O,"attached",[a,t,A,b]);g(A,"attachedHandler",[a,t,b]);if(!b){var c=u.createChildContext(A,void 0,function(a){a.$module=
A;a.$params=K});l(r[0],E,function(a){f.applyBindings(c,a)});e(O,"bindingsApplied",[a,t,A]);g(A,"bindingsAppliedHandler",[a,t])}},U=function(){e(O,"transitionCompleted",[q,t,A]);g(A,"transitionCompletedHandler",[q,t])};if(null!=X){var W=b({node:q,valueAccessor:t,isInitial:v,oldViewModel:C,newViewModel:A},X,q,L,R,w,U);J=s(W)}else J=void 0;J||(w(null),R(null),U())}}.bind(null,G),function(b,c){b==G&&null!=c&&a.q.error(c)}.bind(null,G))},null,{disposeWhenNodeIsRemoved:q});return{controlsDescendantBindings:!0}}};
f.virtualElements.allowedBindings.ojModule=!0})()});