/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojbutton","ojs/ojmenu","ojs/ojlistview"],function(a,f){a.td=function(b,a,e){this.u=b;this.ub=a;this.xO=e};a.td.prototype.Se=function(){this.ub.removeClass("oj-navigationlist-expanded oj-navigationlist-vertical")};a.td.prototype.Ur=function(){};a.td.prototype.Rr=function(){};a.td.prototype.YP=function(){return!1};a.td.prototype.DF=function(){};a.td.prototype.NF=function(b,a){b.attr("aria-selected",a?"true":"false")};a.td.prototype.gF=function(){};
a.td.prototype.dQ=function(){};a.td.prototype.eQ=function(){};a.td.prototype.wp=function(a,c,e){return b.r.wp.apply(this.u,arguments)};a.td.prototype.Wr=function(a){return b.r.Wr.apply(this.u,arguments)};a.td.prototype.Ve=function(a){return b.r.Ve.apply(this.u,arguments)};a.td.prototype.zp=function(a,c){b.r.zp.apply(this.u,arguments)};a.td.prototype.Init=function(){this.ub.addClass("oj-navigationlist-expanded oj-navigationlist-vertical")};a.td.prototype.wh=function(a){return b.r.wh.apply(this.u,arguments)};
a.td.prototype.rv=function(){};a.td.prototype.HP=function(){};a.td.prototype.Ir=function(){};a.fg=function(b,c,e){a.fg.r.constructor.call(this,b,c,e)};a.b.ga(a.fg,a.td,"oj.HorizontalNavListHandler");a.fg.prototype.Se=function(){this.ub.removeClass("oj-navigationlist-expanded oj-navigationlist-horizontal");this.ub.find("."+this.u.Tr).remove()};a.fg.prototype.NF=function(b,a){b.attr("aria-pressed",a?"true":"false")};a.fg.prototype.wp=function(a,c,e){a===f.ui.keyCode.LEFT?a=this.u.Uf()?f.ui.keyCode.DOWN:
f.ui.keyCode.UP:a===f.ui.keyCode.RIGHT&&(a=this.u.Uf()?f.ui.keyCode.UP:f.ui.keyCode.DOWN);a=b.r.wp.call(this.u,a,c,e);"top"===this.u.V.options.edge&&this.u.mb.elem[0].scrollIntoView(!1);return a};a.fg.prototype.Wr=function(a){return a===this.u.LF||a===this.u.iF||a===this.u.nv||a===this.u.Dz};a.fg.prototype.DF=function(a){a=this.u.oE(a);a.attr("role","button");a[0].hasAttribute("aria-selected")&&(a.attr("aria-pressed","false"),a.removeAttr("aria-selected"))};a.fg.prototype.gF=function(){var a=this;
this.u.element.attr("role","toolbar");this.u.element.find("."+this.u.Rf()+":visible").each(function(b){0<b&&a.dT(this,b)})};a.fg.prototype.dT=function(a,b){var e=f(a),g=e.prev();0<b&&e.is(":visible")&&g.length&&!g.is("li."+this.u.Tr)&&e.before('\x3cli role\x3d"separator" class\x3d"'+this.u.Tr+'"\x3e\x3c/li\x3e')};a.fg.prototype.dQ=function(a,b){this.dT(a,b.index)};a.fg.prototype.eQ=function(a){a=f(a);var b=a.prev();b.length&&b.is("li."+this.u.Tr)?b.remove():(a=a.next(),a.is("li."+this.u.Tr)&&a.remove())};
a.fg.prototype.wh=function(a){return this.u.qe(f(a))[0].hasAttribute("aria-pressed")};a.fg.prototype.Init=function(){this.ub.addClass("oj-navigationlist-expanded oj-navigationlist-horizontal")};a.fg.prototype.rv=function(){};a.Yj=function(b,c,e){a.Yj.r.constructor.call(this,b,c,e)};a.b.ga(a.Yj,a.td,"oj.CollapsibleNavListHandler");a.Yj.prototype.Se=function(){this.ub.removeClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};a.Yj.prototype.Init=function(){this.ub.addClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};
a.Yj.prototype.Ur=function(a,c){b.r.dF.apply(this.u,arguments)};a.Yj.prototype.Rr=function(a,c){b.r.bF.apply(this.u,arguments)};a.Yj.prototype.YP=function(a,b,e,g){var h=0<e.children("."+this.u.Li()).length;if(b===this.u.nv||b===this.u.Dz)return b===this.u.nv&&!this.u.Uf()||b===this.u.Dz&&this.u.Uf()?this.u.Ve(e)===this.u.cj&&this.u.an(e,a,!0,g,!0,!0):this.u.Ve(e)===this.u.bj&&this.u.rp(e,a,!0,g,!0,!0,!0),!0;if(h&&(b===f.ui.keyCode.ENTER||b===f.ui.keyCode.SPACE)){if(0>=e.length)return;this.u.Ve(e)===
this.u.bj?this.u.rp(e,null,!0,g,!0,!0,!0):this.u.Ve(e)===this.u.cj&&this.u.an(e,null,!0,g,!0,!0);return!0}return!1};a.Yj.prototype.rv=function(){};a.ed=function(b,c,e){a.ed.r.constructor.call(this,b,c,e);this.AO=[]};a.b.ga(a.ed,a.Yj,"oj.SlidingNavListHandler");a.ed.prototype.Se=function(){this.ub.removeClass("oj-navigationlist-slider oj-navigationlist-vertical");this.sD.remove()};a.ed.prototype.R0=function(a,b,e){var f=this,h=this.u.UN(),k=h.outerWidth()/2,l=this.u.Uf();b||(k*=-1);l?(h.css({"margin-right":k}),
h.animate({"margin-right":"0px"},400,"swing",function(){f.lD(a,b,e)})):(h.css({"margin-left":k}),h.animate({"margin-left":"0px"},400,"swing",function(){f.lD(a,b,e)}))};a.ed.prototype.lD=function(a,b,e){null!==this.u.ue&&(e&&(e=this.u.cd(e[0]),this.u.yh("currentItem",e)),b?this.u.eF(a.children("."+this.u.Li())):this.u.cF(a.children("."+this.u.Li())))};a.ed.prototype.Ur=function(a,b){var e=f(a).parents(".oj-navigationlist-item-element:first"),g=e.children("."+this.u.Li()),h,k=null,l=e.closest("."+this.u.kn);
if(0<l.length){l.removeClass(this.u.kn);e.addClass(this.u.kn);var k=g.find("."+this.u.Rf()+":eq(0)"),m=e.parentsUntil(l,"ul"),m=l.is(this.u.element)?m.get().concat(l.get()):m.get(),n=this,p,m=f(m.reverse());m.each(function(a,b){h=f(b).is(n.u.element)?n.u.mE():n.u.NN(f(b).parent());p=a===m.length-1?e:f(m.get(a+1)).parent();n.I$(n.u.cd(p[0]),n.u.NN(p),h);n.AO.push(p)})}b?this.R0(e,!0,k):this.lD(e,!0,k);this.u.element.focus();e.siblings().attr("aria-hidden","true");e.children("."+this.u.zg()).children("."+
this.u.ak).attr("aria-hidden","true");g.removeAttr("aria-hidden");a.css("display","");e.addClass("oj-skipfocus")};a.ed.prototype.Rr=function(a,b){var e=a.children("."+this.u.Li()),f=a.parent();a.children("."+this.u.zg()).children("."+this.u.ak).removeAttr("aria-hidden");e.attr("aria-hidden","true");a.siblings().removeAttr("aria-hidden");a.removeClass("oj-skipfocus");a.removeClass(this.u.kn);0===a.closest("."+this.u.kn).length&&(f.closest("."+this.u.Rf()).addClass(this.u.kn),this.u.element.is(f)&&
this.u.element.addClass(this.u.kn));b?this.R0(a,!1,e.parent()):this.lD(a,!1,e.parent());this.pka();this.u.element.focus()};a.ed.prototype.NF=function(a,b){b?a.attr("aria-describedby","selectedLabel"):a.removeAttr("aria-describedby")};a.ed.prototype.Ve=function(a){a=this.u.qe(a).attr("aria-expanded");return"true"===a?this.u.cj:"false"===a?this.u.bj:this.u.wQ};a.ed.prototype.zp=function(a,b){b===this.u.cj?(this.u.qe(a).attr("aria-expanded","true"),a.removeClass(this.u.EP).addClass(this.u.NP)):b===this.u.bj&&
(this.u.qe(a).attr("aria-expanded","false"),a.removeClass(this.u.NP).addClass(this.u.EP))};a.ed.prototype.DF=function(a,b){var e=this.u.qe(a);e.attr("role","menuitem");b.attr("id")||b.uniqueId();var f=a.children("."+this.u.Li());0<f.length&&(e.attr("aria-haspopup","true"),f.attr("role","menu"),f.css("display",""),a.removeAttr("aria-expanded"),e.attr("aria-expanded","false"))};a.ed.prototype.gF=function(){this.u.element.attr("role","menu")};a.ed.prototype.Init=function(a){this.ub.addClass("oj-navigationlist-slider oj-navigationlist-vertical");
a.element.addClass("oj-navigationlist-current");this.Aaa(a);this.iha()};a.ed.prototype.Aaa=function(a){var b;this.sD=f(document.createElement("div"));this.sD.addClass("oj-navigationlist-toolbar");this.gm=f(document.createElement("a"));this.Fx=f(document.createElement("span"));this.Fx.addClass("oj-navigationlist-previous-icon oj-component-icon oj-clickable-icon-nocontext").attr("role","img").attr("alt",this.xO.A("previousIcon"));this.Fx.hide();this.gm.addClass("oj-navigationlist-previous-link").attr("tabindex",
"-1").append(this.Fx);this.Zw=f(document.createElement("label"));this.Zw.addClass("oj-navigationlist-current-header").text(this.u.mE());this.HD=f(document.createElement("span"));this.HD.attr("role","separator").attr("aria-orientation","vertical").addClass("oj-navigationlist-toolbar-separator");this.Ih=f(document.createElement("button"));this.Ih.addClass("oj-navigationlist-hierarchical-button");this.Ef=f(document.createElement("ul"));this.Ef.addClass("oj-navigationlist-hierarchical-menu").hide();b=
f(document.createElement("label"));b.addClass("oj-helper-hidden-accessible").attr("aria-hidden","true").attr("id","selectedLabel");b.text(this.xO.A("selectedLabel"));this.gm.append(this.Zw);this.sD.append(this.gm).append(this.HD).append(this.Ih).append(this.Ef).append(b);this.ub.prepend(this.sD);this.iD(a.hierarchyMenuDisplayThresholdLevel)};a.ed.prototype.HP=function(){var a=this.AO.pop();a&&this.u.an(a,null,!0,null,!0,!0)};a.ed.prototype.iha=function(){var a=this,b=this.Ef.uniqueId().attr("id");
this.Ef.ojMenu({openOptions:{position:{my:"end top",at:"end bottom"}},select:function(b,c){for(var h=c.item.nextAll(),k,l,m=a.AO,n=c.item.data("key");0<m.length&&(l=m.pop(),k=a.u.cd(l[0]),a.u.an(f(l),null,!0,k,!0,!0),n!==k););h.remove();c.item.remove();a.Ef.ojMenu("refresh")}});this.Ih.ojButton({label:this.xO.A("hierMenuBtnLabel"),display:"icons",icons:{start:"oj-fwk-icon oj-hier-icon"},menu:"#"+b,disabled:!0,chroming:"half"})};a.ed.prototype.I$=function(a,b,e){if(this.Ih){var g=this.Ef.find("li").length,
h=f(document.createElement("li")),k=f(document.createElement("a"));k.attr("href","#");h.append(k);if(0<g){for(var l=0;l<g;l++)0<l&&k.append(f(document.createElement("span")).addClass("oj-navigationlist-hvitem-space"));k.append(f(document.createElement("span")).addClass("oj-menu-item-icon oj-icon oj-navigationlist-level-indicator"))}g=f(document.createElement("span")).addClass("oj-navigationlist-hierarchical-menu-label");g.text(e);k.append(g);h.data("key",a);this.Ef.append(h);this.Ef.ojMenu("refresh");
this.iD(this.u.Xd("hierarchyMenuDisplayThresholdLevel"));this.Ih.ojButton("option","disabled",!1);this.Fx.show();this.gm.attr("tabindex","0");this.Zw.text(b)}};a.ed.prototype.Ir=function(a){this.u.Xd("hierarchyMenuDisplayThresholdLevel")!==a.hierarchyMenuDisplayThresholdLevel&&this.iD(a.hierarchyMenuDisplayThresholdLevel)};a.ed.prototype.iD=function(a){var b=this.Ef.find("li").length;-1===a||b<a?(this.HD.hide(),this.Ih.hide()):b>=a&&(this.HD.show(),this.Ih.show())};a.ed.prototype.pka=function(){if(this.Ih){var a=
this.Ef.find("li").last().remove();this.Ef.ojMenu("refresh");this.iD(this.u.Xd("hierarchyMenuDisplayThresholdLevel"));0===this.Ef.children("li").length?(this.Ih.ojButton("option","disabled",!0),this.Fx.hide(),this.gm.attr("tabindex","-1"),this.Zw.text(this.u.mE())):this.Zw.text(a.children("a").text())}};a.ed.prototype.rv=function(a,b){a.removeClass(this.u.kn);b.removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-describedby").removeAttr("aria-hidden")};var b=function(b,c){function e(){}
a.b.ga(e,b,"");f.extend(e.prototype,c);return e}(a.SK,{ak:"oj-navigationlist-item-content",NP:"oj-expanded",EP:"oj-collapsed",kn:"oj-navigationlist-current",Tr:"oj-navigationlist-divider",D7:"oj-navigationlist-category-divider",hG:"oj-navigationlist-item-label",vR:"oj-navigationlist-icon-only",DR:"oj-navigationlist-item-icon",Dra:"oj-navigationlist-horizontal",TR:"oj-navigationlist-has-icons",UR:"oj-navigationlist-item-no-icon",c9:"oj-navigationlist-item-title",VR:"oj-navigationlist",WR:"oj-navigationlist-touch",
d9:"oj-navigationlist-listview-container",Wz:"IsTitleAttrDueToTruncation",SF:"oj-navigationlist-app-level",sG:"oj-navigationlist-page-level",nG:"navigationListItemIconHastitle",e9:"oj-navigationlist-nofollow-link",NN:function(a){a=this.jE(a);return a.is("a")?f.trim(a.text()):f.trim(a.find("."+this.c9).text())},jE:function(a){var b=a.children("."+this.ak);0===b.length&&(b=a.children("."+this.zg()).children("."+this.ak),0===b.length&&(b=a.children("."+this.zg()).children(":not(."+this.xm()+"):not(."+
this.Mj()+")")));return b},Uf:function(){return"rtl"===this.V.dc()},fp:function(){this.Zb.gF();b.r.fp.apply(this,arguments)},o4:function(a,b){this.Zb.dQ(a,b)},mO:function(a){this.Zb.eQ(a);b.r.mO.apply(this,arguments)},T_:function(a){var b=a.children();a.removeAttr("style").removeClass(this.TR).removeAttr("aria-hidden");for(a=0;a<b.length;a++){var e=b[a],e=f(e);if(e.hasClass(this.Tr))e.remove();else{var g=this.jE(e);g.removeClass(this.ak).removeClass(this.UR).removeAttr("aria-haspopup");var h=g.children("."+
this.DR);h&&0<h.length&&(h.removeAttr("role"),h.removeAttr("aria-label"),this.yka(h));e.removeClass("oj-default").removeAttr("role").removeAttr("aria-disabled").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-pressed");h=this.qe(e);h.removeAttr("role").removeAttr("aria-hidden").removeAttr("aria-pressed");g.children("."+this.hG).contents().unwrap();h.data(this.Wz)&&h.removeAttr("title");h=e.children("ul");0<h.length?(this.Zb.rv(e,g,h),this.T_(h)):this.Zb.rv(e,g)}}},Az:function(a){return a.hasClass(this.ak)||
a.hasClass(this.xm())||a.hasClass(this.Mj())?!1:b.r.Az.apply(this,arguments)},cQ:function(a){return a.prop("nodeName").match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&!a.hasClass(this.ak)||a.hasClass("oj-component")},jja:function(a){var b={drillMode:"none"!==a.drillMode?"collapsible":"none",selection:null!==a.selection?[a.selection]:[],item:a.item,data:a.data,selectionMode:"single"};b.element=this.oo;b.item.focusable=function(a){return f(a.data).is("li")?!f(a.data).hasClass("oj-disabled"):!f(a.parentElement).hasClass("oj-disabled")};
return b=f.extend(f.extend({},a),b)},mE:function(){return this.V.options.rootLabel?this.V.options.rootLabel:this.V.A("defaultRootLabel")},vv:function(){var a=this.V.element.attr("aria-labelledby");a?(this.element.attr("aria-labelledby",a),this.V.element.removeAttr("aria-labelledby")):this.element.attr("aria-label",this.mE());b.r.vv.apply(this,arguments)},MF:function(){this.element.attr("aria-labelledby")&&(this.V.element.attr("aria-labelledby",this.element.attr("aria-labelledby")),this.element.removeAttr("aria-labelledby"));
this.element.attr("aria-label")&&this.element.removeAttr("aria-label");b.r.MF.apply(this,arguments)},Em:function(d){var c=this,e=d.V.element;e.addClass(this.VR);a.v.Ud()&&e.addClass(this.WR);this.oo=e.children("ul:first");0===this.oo.length&&(this.oo=f(document.createElement("ul")),e.append(this.oo));e=f(document.createElement("div"));e.addClass(this.d9);this.oo.wrap(e);d=this.jja(d);b.r.Em.call(this,d);this.element.removeClass("oj-component-initnode");this.V._on(this.V.element,{touchstart:function(a){(a=
c.Zh(f(a.target)))&&!a.hasClass("oj-disabled")&&c.xp(a,"oj-active",!0)},touchend:function(a){a=c.Zh(f(a.target));c.xp(a,"oj-active",!1)},mousedown:function(a){(a=c.Zh(f(a.target)))&&!a.hasClass("oj-disabled")&&c.xp(a,"oj-active",!0)},mouseup:function(a){a=c.Zh(f(a.target));c.xp(a,"oj-active",!1)},"click .oj-navigationlist-previous-link":function(){c.RH()},"keydown .oj-navigationlist-previous-link":function(a){a.keyCode===f.ui.keyCode.ENTER&&c.RH()},"keydown .oj-navigationlist-element":function(a){a.keyCode!==
f.ui.keyCode.ESCAPE||a.isDefaultPrevented()||c.RH()},"mouseenter a.oj-navigationlist-item-content":function(a){a=f(a.currentTarget);var b=a.find("."+c.hG);b[0].offsetWidth<b[0].scrollWidth&&!a.attr("title")&&(a.attr("title",b.text().trim()),a.data(c.Wz,"true"))},"mouseleave a.oj-navigationlist-item-content":function(a){a=f(a.currentTarget);a.data(c.Wz)&&(a.removeData(c.Wz),a.removeAttr("title"))}})},RH:function(){this.Zb.HP()},gY:function(){var b=this.V.options.drillMode,c=this.V.options.edge;this.Zb=
"sliding"===b?new a.ed(this,this.V.element,this.V):"collapsible"===b?new a.Yj(this,this.V.element,this.V):"none"===b&&"top"===c?new a.fg(this,this.V.element,this.V):new a.td(this,this.V.element,this.V);this.Zb.Init(this.options);this.r0(this.V.options.navigationLevel)},r0:function(a){"none"===this.V.options.drillMode&&("application"===a?(this.V.element.addClass(this.SF),this.V.element.removeClass(this.sG)):"page"===a&&(this.V.element.addClass(this.sG),this.V.element.removeClass(this.SF)))},tu:function(){this.gY();
b.r.tu.apply(this,arguments)},VP:function(){return"oj-navigationlist-listview"},qF:function(){return"oj-navigationlist-element"},Oj:function(){return"oj-navigationlist-item"},Wk:function(){return"oj-navigationlist-focused-element"},Rf:function(){return"oj-navigationlist-item-element"},Mj:function(){return"oj-navigationlist-collapse-icon"},xm:function(){return"oj-navigationlist-expand-icon"},KN:function(a){return"oj-navigationlist-depth-"+a},zg:function(){return"oj-navigationlist-group-item"},Li:function(){return"oj-navigationlist-group"},
Fu:function(){return"oj-navigationlist-collapsible-transition"},lr:function(){return this.Fu()},dF:function(a,b){this.Zb.Ur(a,b)},bF:function(a,b){this.Zb.Rr(a,b)},wp:function(a,b,e){return this.Zb.wp(a,b,e)},Wr:function(a){return this.Zb.Wr(a)},Ve:function(a){return this.Zb.Ve(a)},zp:function(a,b){this.Zb.zp(a,b)},vF:function(a){var c=this.Zh(f(a.target));null!=c&&0!==c.length&&(this.gi(c)?a.preventDefault():(this.cd(c[0]),this.Az(f(a.target))||(c=this.jE(c).attr("href"),c&&"#"!==c&&0===a.button&&
(a.shiftKey||a.ctrlKey)||(b.r.vF.apply(this,arguments),a.preventDefault()))))},ZP:function(a){var b,e,g;b=a.keyCode;e=this.mb.elem;g=this.mb.key;if(b===f.ui.keyCode.HOME||b===f.ui.keyCode.END){var h;h=b===f.ui.keyCode.HOME?this.element.find("."+this.ak+":visible").first().closest("."+this.Rf()):this.element.find("."+this.ak+":visible").last().closest("."+this.Rf());h=this.cd(h[0]);this.yh("currentItem",h);a.preventDefault()}else h=this.aQ(a),b=this.Zb.YP(a,b,e,g),!0!==h&&!0!==b||a.preventDefault()},
Gz:function(a,c,e){var f=this.mb.elem;this.wh(f[0])&&!this.LY(f)&&this.JI(a,f)&&(b.r.Gz.apply(this,arguments),this.rK(f))},xp:function(a,b,e){var g;a=f(a);"oj-selected"===b&&this.Zb.NF(this.qe(a),e);g=a.children("."+this.zg());0<g.length&&(a=f(g[0]));e?a.addClass(b):a.removeClass(b);a.hasClass("oj-selected")||a.hasClass("oj-hover")||a.hasClass("oj-active")||a.hasClass("oj-disabled")?a.removeClass("oj-default"):a.addClass("oj-default")},wh:function(a){return!f(a).hasClass("oj-disabled")&&this.Zb.wh(f(a))},
mn:function(a,b,e){return"ready"!==a?this.V._trigger(a,b,e):!0},yh:function(a,b,e){if("selection"===a){var f=e._context,h=f&&f.Kj&&f.Kj.items;h&&(f.Kj.item=h,f.Kj.items=void 0);b&&0<b.length?this.V.option(a,b[0],e):this.V.option(a,null,e)}else this.V.option(a,b,e);this.options[a]=b},zQ:function(a){return null!=a.data||null!=a.drillMode||null!=a.item||null!=a.display||null!=a.edge},Ir:function(a,c){var e={iP:[]},g;void 0!==a.hierarchyMenuDisplayThresholdLevel&&this.Zb.Ir(a);void 0!==a.navigationLevel&&
this.r0(a.navigationLevel);if(void 0!==a.selection)if(g=a.selection){var h=this.Xd("selection");h&&0!==h.length&&h[0]===g?delete a.selection:(h=this.Jd(g))&&this.wh(h)?this.JI(null,f(h))?(a.selection=[g],this.rK(f(h))):(delete a.selection,e.iP.push("selection")):(delete a.selection,e.iP.push("selection"))}else a.selection=[];e.Xpa=b.r.Ir.call(this,a,c);void 0!==g&&(a.selection=g);return e},Xd:function(a){var b=this.V.option(a);return"selection"===a?b?[b]:[]:null===b?this.options[a]:b},Tf:function(){return a.Components.Tf(this.V.element)},
uv:function(a,c){if(!a.hasClass("oj-disabled")&&this.wh(a[0])){var e=this.cd(a[0]);this.yh("currentItem",e);!this.LY(a)&&this.JI(c,a)&&(b.r.uv.apply(this,arguments),this.rK(a))}},JI:function(a,b){var e=this.cd(b[0]);return this.mn("beforeSelect",a,{item:b,key:e})},rK:function(a){return this.V.element.hasClass(this.e9)?!1:(a=this.jE(a).attr("href"))&&"#"!==a?(window.location.href=a,!0):!1},LY:function(a){var b;b=this.Xd("selection");a=this.cd(a[0]);return-1<b.indexOf(a)?!0:!1},Kla:function(a,b){a.attr("title")||
a.attr("title",b)},yka:function(a){a.data(this.nG)?a.removeData(this.nG):a.removeAttr("title")},$y:function(a,c){var e=f(a);if(e.hasClass(this.D7))e.removeClass(this.Rf()),e.removeClass(this.Wk()),e.removeClass(this.Oj()),e.removeAttr("aria-selected"),e.children().remove(),e.attr("role","separator");else{var g=this.Mj(),h=this.xm(),k=this.DR,l=e.children("."+this.zg()),m;0<l.length?(l.addClass(this.Oj()),m=l.children(":not(."+h+"):not(."+g+")"),h=l.children("."+h),0===h.length&&(h=l.children("."+
g)),h.attr("role","presentation"),h.removeAttr("aria-labelledby"),e.hasClass("oj-disabled")&&l.addClass("oj-disabled")):m=e.children().first();m.addClass(this.ak);g=m.wrapInner('\x3cspan class\x3d"'+this.hG+'"\x3e\x3c/span\x3e').find("."+k);0<g.length?(g.insertBefore(g.parent()),g.attr("title")&&g.data(this.nG,g.attr("title")),"icons"===this.V.options.display&&(this.V.element.addClass(this.vR),k=this.NN(e),g.attr("aria-label",k),g.attr("role","img"),this.Kla(g,k)),e.closest("ul").addClass(this.TR)):
m.addClass(this.UR);e.hasClass("oj-disabled")?this.qe(e).attr("aria-disabled","true"):0<l.length?l.addClass("oj-default"):e.addClass("oj-default");this.Zb.DF(e,m);b.r.$y.apply(this,arguments)}},getNodeBySubId:function(a){var b;if(null===a)return this.element?this.element[0]:null;b=a.subId;return"oj-navigationlist-item"===b?(a=a.key,a=this.Jd(a)):"oj-navigationlist-previous-link"===b?this.Zb.gm?this.Zb.gm[0]:null:"oj-navigationlist-hierarchical-button"===b?this.Zb.Ih?this.Zb.Ih[0]:null:"oj-navigationlist-hierarchical-menu"===
b?this.Zb.Ef?this.Zb.Ef[0]:null:null},getSubIdByNode:function(a){if(this.Zb.gm&&this.Zb.gm[0]===a)return{subId:"oj-navigationlist-previous-link"};if(this.Zb.Ih&&this.Zb.Ih[0]===a)return{subId:"oj-navigationlist-hierarchical-button"};if(this.Zb.Ef&&this.Zb.Ef[0]===a)return{subId:"oj-navigationlist-hierarchical-menu"};a=this.Zh(a);return null!=a&&0<a.length&&(a=this.cd(a[0]),null!=a)?{subId:"oj-navigationlist-item",key:a}:null},getContextByNode:function(a){return(a=b.r.getContextByNode.call(this,a))&&
"oj-listview-item"==a.subId?(a.subId="oj-navigationlist-item",a):null},refresh:function(){this.M_();this.gY();b.r.refresh.apply(this,arguments)},M_:function(){this.V.element.removeClass(this.vR);this.V.element.removeClass(this.SF);this.V.element.removeClass(this.sG);this.T_(this.element);this.Zb.Se()},destroy:function(){this.M_();b.r.destroy.apply(this,arguments);this.oo.unwrap();this.oo.is(":empty")&&this.oo.remove();this.V.element.removeClass(this.VR+" "+this.WR);this.V._off(this.element,"click");
this.V._off(this.element,"focus");this.V._off(this.element,"blur");this.V._off(this.element,"mouseover");this.V._off(this.element,"mousein");this.V._off(this.element,"mouseout");this.V._off(this.element,"keydown")}});(function(){a.ya("oj.ojNavigationList",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{currentItem:null,drillMode:"none",edge:"start",hierarchyMenuDisplayThresholdLevel:0,rootLabel:null,selection:null,expanded:"auto",data:null,display:"all",navigationLevel:"page",item:{renderer:null,
selectable:!0},beforeSelect:null,beforeCollapse:null,beforeCurrentItem:null,collapse:null,beforeExpand:null,expand:null,optionChange:null},_ComponentCreate:function(){this._super();this.Ba()},rf:function(){this._super();this.Wf.tu()},uf:function(a,b,e){this.Wf.T4(a,b,e)},Ba:function(){for(var a in this.options)this.G1(a,this.options[a]);this.ID(this.options.drillMode,this.options.display,this.options.edge);this.Wf=new b;a={V:this};a=f.extend(this.options,a);this.Wf.Em(a)},getNodeBySubId:function(a){return this.Wf.getNodeBySubId(a)},
getSubIdByNode:function(a){return this.Wf.getSubIdByNode(a)},getContextByNode:function(a){return this.Wf.getContextByNode(a)},expand:function(a,b){this.Wf.uN(a,b,!0,!0)},collapse:function(a,b){this.Wf.i2(a,b,!0)},getExpanded:function(){return this.Wf.getExpanded()},ID:function(a,b,e){if("none"!==a){if("icons"===b)throw"Icon only navigation list should have drillMode set to 'none'.";if("top"===e)throw"Horizontal navigation list should have drillMode set to 'none'.";}},G1:function(a,b){var e=!0;"drillMode"===
a?e="none"===b||"collapsible"===b||"sliding"===b:"display"===a?e="all"===b||"icons"===b:"edge"===a&&(e="top"===b||"start"===b);if(!e)throw"Invalid value: "+b+" for key: "+a;},_setOption:function(a,b){this.G1(a,b);switch(a){case "drillMode":this.ID(b,this.options.display,this.options.edge);break;case "display":this.ID(this.options.drillMode,b,this.options.edge);break;case "edge":this.ID(this.options.drillMode,this.options.display,b)}return this._super(a,b)},_setOptions:function(a,b){var e=this.Wf.Ir(a,
b),f;for(f in a)0>e.iP.indexOf(f)&&this._setOption(f,a[f],b);e.Xpa&&this.Wf.refresh();return this},oi:function(){this.Wf.U4()},Al:function(){},refresh:function(){this._super();this.Wf.refresh()},whenReady:function(){return this.Wf.whenReady()},_destroy:function(){this.Wf.destroy();this._super();delete this.Wf}});a.Components.Tm({ojNavigationList:{hierarchyMenuDisplayThresholdLevel:a.Components.nh(function(){return a.Ee.Yk("navigationList").hierarchyMenuDisplayThresholdLevel})}})})()});