/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdatasource-common"],function(a,f){a.Te=function(a,d){this.Upa=a;this.$b=d};o_("EmptyNodeSet",a.Te,a);a.Te.prototype.getParent=function(){return this.Upa};a.b.g("EmptyNodeSet.prototype.getParent",{getParent:a.Te.prototype.getParent});a.Te.prototype.ta=function(){return this.$b};a.b.g("EmptyNodeSet.prototype.getStart",{ta:a.Te.prototype.ta});a.Te.prototype.R=function(){return 0};a.b.g("EmptyNodeSet.prototype.getCount",{R:a.Te.prototype.R});
a.Te.prototype.getData=function(){return null};a.b.g("EmptyNodeSet.prototype.getData",{getData:a.Te.prototype.getData});a.Te.prototype.getMetadata=function(){return null};a.b.g("EmptyNodeSet.prototype.getMetadata",{getMetadata:a.Te.prototype.getMetadata});a.Ue=function(a,d){this.Ab=a;this.$b=d};o_("FlattenedNodeSet",a.Ue,a);a.Ue.prototype.getParent=function(){return this.Ab.getParent()};a.b.g("FlattenedNodeSet.prototype.getParent",{getParent:a.Ue.prototype.getParent});a.Ue.prototype.ta=function(){return void 0!=
this.$b?this.$b:this.Ab.ta()};a.b.g("FlattenedNodeSet.prototype.getStart",{ta:a.Ue.prototype.ta});a.Ue.prototype.R=function(){void 0===this.xE&&(this.xE=this.gW(this.Ab,0),void 0!=this.$b&&(this.xE-=this.$b));return this.xE};a.b.g("FlattenedNodeSet.prototype.getCount",{R:a.Ue.prototype.R});a.Ue.prototype.gW=function(a,d){var c,e,f,h;c=a.ta();e=a.R();d+=e;if(a.Qf)for(f=0;f<e;f++)h=a.Qf(f+c),null!=h&&(d=this.gW(h,d));return d};a.Ue.prototype.getData=function(a){return this.WI(this.Ab,a,{index:this.Ab.ta()},
this.$a)};a.b.g("FlattenedNodeSet.prototype.getData",{getData:a.Ue.prototype.getData});a.Ue.prototype.getMetadata=function(a){return this.WI(this.Ab,a,{index:this.Ab.ta()},this.Qw)};a.b.g("FlattenedNodeSet.prototype.getMetadata",{getMetadata:a.Ue.prototype.getMetadata});a.Ue.prototype.Qw=function(a,d){return a.getMetadata(d)};a.Ue.prototype.$a=function(a,d){return a.getData(d)};a.Ue.prototype.WI=function(a,d,c,e){var f,h,k,l;f=a.ta();h=a.R();for(k=0;k<h;k++){l=c.index;if(l===d)return e.call(this,
a,k+f);c.index=l+1;if(a.Qf&&(l=a.Qf(k+f),null!=l&&(l=this.WI(l,d,c,e),null!=l)))return l}return null};a.Qg=function(a,d,c){this.Wo=a;this.HO=d;this.GO=this.sda(c)};o_("MergedNodeSet",a.Qg,a);a.Qg.prototype.sda=function(a){var d,c,e;d=this.Wo.ta();for(c=d+this.Wo.R();d<c;d++)if(e=this.Wo.getMetadata(d).key,a===e)return d;return c-1};a.Qg.prototype.getParent=function(){return this.Wo.getParent()};a.b.g("MergedNodeSet.prototype.getParent",{getParent:a.Qg.prototype.getParent});a.Qg.prototype.ta=function(){return this.Wo.ta()};
a.b.g("MergedNodeSet.prototype.getStart",{ta:a.Qg.prototype.ta});a.Qg.prototype.R=function(){return this.Wo.R()+this.HO.R()};a.b.g("MergedNodeSet.prototype.getCount",{R:a.Qg.prototype.R});a.Qg.prototype.getData=function(a){a=this.UW(a);return a.set.getData(a.index)};a.b.g("MergedNodeSet.prototype.getData",{getData:a.Qg.prototype.getData});a.Qg.prototype.getMetadata=function(a){a=this.UW(a);return a.set.getMetadata(a.index)};a.b.g("MergedNodeSet.prototype.getMetadata",{getMetadata:a.Qg.prototype.getMetadata});
a.Qg.prototype.UW=function(a){if(a<=this.GO)return{set:this.Wo,index:a};var d=this.HO.R();return a>this.GO+d?{set:this.Wo,index:a-d}:{set:this.HO,index:a-(this.GO+1)}};a.Xe=function(a,d,c,e){this.Ab=a;this.Rj=d;this.Qu=c;this.Pi=e};o_("NodeSetWrapper",a.Xe,a);a.Xe.prototype.getParent=function(){return this.Ab.getParent()};a.b.g("NodeSetWrapper.prototype.getParent",{getParent:a.Xe.prototype.getParent});a.Xe.prototype.ta=function(){return null!=this.Qu?this.Qu.start:this.Ab.ta()};a.b.g("NodeSetWrapper.prototype.getStart",
{ta:a.Xe.prototype.ta});a.Xe.prototype.R=function(){var a,d;a=this.Ab.ta();d=this.Ab.R();null!=this.Qu&&(this.Qu.start>a?d=Math.min(0,d-(this.Qu.start-a)):this.Qu.start<a&&(d=0));return d};a.b.g("NodeSetWrapper.prototype.getCount",{R:a.Xe.prototype.R});a.Xe.prototype.getData=function(a){return this.Ab.getData(a)};a.b.g("NodeSetWrapper.prototype.getData",{getData:a.Xe.prototype.getData});a.Xe.prototype.getMetadata=function(a){var d;d=this.Ab.getMetadata(a);d.index=a;d.parentKey=this.getParent();this.Rj.call(null,
d.key,d);return d};a.b.g("NodeSetWrapper.prototype.getMetadata",{getMetadata:a.Xe.prototype.getMetadata});a.Xe.prototype.Qf=function(b){return null!=this.Pi&&-1!=this.Pi.indexOf(this.Ab.getMetadata(b).key)||!this.Ab.Qf||(b=this.Ab.Qf(b),null==b)?null:new a.Xe(b,this.Rj,null,this.Pi)};a.b.g("NodeSetWrapper.prototype.getChildNodeSet",{Qf:a.Xe.prototype.Qf});a.ca=function(b,d){this.Dd=b;this.fz=d||{};a.ca.r.constructor.call(this)};o_("FlattenedTreeDataSource",a.ca,a);a.b.ga(a.ca,a.Xi,"oj.FlattenedTreeDataSource");
a.ca.prototype.Init=function(){var b;a.ca.r.Init.call(this);this.Dd.on("change",this.fga.bind(this));this.BO=parseInt(this.fz.fetchSize,10);isNaN(this.BO)&&(this.BO=25);this.xr=parseInt(this.fz.maxCount,10);isNaN(this.xr)&&(this.xr=500);b=this.fz.expanded;Array.isArray(b)?this.Hm=b:("all"===b&&(this.Pi=[]),this.Hm=[]);this.Gm=[]};a.b.g("FlattenedTreeDataSource.prototype.Init",{Init:a.ca.prototype.Init});a.ca.prototype.handleEvent=function(b,d){return a.ca.r.handleEvent.call(this,b,d)};a.b.g("FlattenedTreeDataSource.prototype.handleEvent",
{handleEvent:a.ca.prototype.handleEvent});a.ca.prototype.Se=function(){delete this.Gm;delete this.Hm;delete this.Pi;this.Dd.off("change");this.Dd.Se&&this.Dd.Se()};a.b.g("FlattenedTreeDataSource.prototype.Destroy",{Se:a.ca.prototype.Se});a.ca.prototype.MN=function(){return this.BO};a.ca.prototype.g3=function(){return this.Hm};a.b.g("FlattenedTreeDataSource.prototype.getExpandedKeys",{g3:a.ca.prototype.g3});a.ca.prototype.Jy=function(a){return null!=this.fz?this.fz[a]:null};a.b.g("FlattenedTreeDataSource.prototype.getOption",
{Jy:a.ca.prototype.Jy});a.ca.prototype.getWrappedDataSource=function(){return this.Dd};a.b.g("FlattenedTreeDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ca.prototype.getWrappedDataSource});a.ca.prototype.$I=function(a){var d,c;d=this.MN();c=this.xr;return-1===d?-1===a?c:a:-1===a?Math.min(d,a):d};a.ca.prototype.No=function(a,d){this.Jt()?this.nda(a,d):this.mda(a,d)};a.ca.prototype.mda=function(b,d){var c,e,f,h,k,l;if(b.start>this.Je()){c=this.kJ();if(0>this.Je()){b.count=Math.min(c,
b.count);this.Dd.Nf(null,b,{success:function(a){this.bo(a,null,0,b,0,d)}.bind(this),error:function(a){this.Yl(a,d)}.bind(this)});return}if(0<c){e=this.AW();f=e.parent;h=this.Dd.ff(f);k=e.index;l=e.depth;-1===h||k<h-1?(e=this.$I(h),b.start=k+1,b.count=-1===h?e:Math.min(c,Math.min(e,h-b.start)),this.Dd.Nf(f,b,{success:function(a){this.bo(a,f,l,b,h,d)}.bind(this),error:function(a){this.Yl(a,d)}.bind(this)})):k===h-1?(c=new a.Te(null,b.start),null!=d&&null!=d.success&&d.success.call(null,c)):(c=this.EV(f,
l,d,c),c||(c=new a.Te(null,b.start),null!=d&&null!=d.success&&d.success.call(null,c)));return}}this.ZN(b,d)};a.ca.prototype.rd=function(a,d,c){return this.Dd.rd(a,d,c)};a.b.g("FlattenedTreeDataSource.prototype.moveOK",{rd:a.ca.prototype.rd});a.ca.prototype.move=function(a,d,c,e){this.Dd.move(a,d,c,e)};a.b.g("FlattenedTreeDataSource.prototype.move",{move:a.ca.prototype.move});a.ca.prototype.kJ=function(){return this.xr-(this.Je()+1)};a.ca.prototype.Yl=function(a,d){null!=d&&null!=d.error&&d.error.call(null,
a)};a.ca.prototype.bo=function(b,d,c,e,f,h){var k;k=[];b=new a.Xe(b,this.Qy.bind(this),e);this.sja(b,d,c,k);-1===f&&0===b.R()&&null!=d&&0<c?(k=this.EV(d,c,h))||null!=h&&null!=h.success&&h.success.call(null,b):0===k.length?null!=h&&null!=h.success&&h.success.call(null,b):(d=[],d.push(k),k={},k.callbacks=h,k.nodeSet=b,k.keys=[],this.e1(d,k))};a.ca.prototype.ff=function(a){return this.Dd.ff(a)};a.b.g("FlattenedTreeDataSource.prototype.getChildCount",{ff:a.ca.prototype.ff});a.ca.prototype.EV=function(a,
d,c,e){var f,h,k,l,m,n,p,r,s;void 0===e&&(e=this.kJ());this.tha()&&(f={queueOnly:!0});h=s=this.$I(-1);for(k=this.Je()-1;0<=k;k--)if(l=this.ah(k),m=l.depth,m<d&&(a=l.parent,n=this.Dd.ff(a),l=l.index,(p=-1===n)||l<n-1)){r={};r.start=l+1;p?(r.count=Math.min(e,Math.max(0,h)),f=void 0):r.count=Math.min(e,Math.min(h,n-r.start));if(0==r.count)break;this.Dd.Nf(a,r,{success:function(d){this.bo(d,a,m,r,n,c)}.bind(this),error:function(a){this.Yl(a,c)}.bind(this)},f);d=m;h=Math.max(0,h-r.count);if(p||0===m||
0===h)break}void 0!=f&&this.Dd.Nf(a,{start:r.count,count:0},{success:function(d){this.bo(d,a,m,r,n,c)}.bind(this),error:function(a){this.Yl(a,c)}.bind(this)});return h!=s};a.ca.prototype.sja=function(a,d,c,e){var f,h,k,l;f=a.ta();h=a.R();for(k=0;k<h;k++)l=a.getMetadata(f+k),l=l.key,this.BA(l,c,f+k,d),this.gx(l)&&e.push(l)};a.ca.prototype.Qy=function(a,d){this.gx(a)&&!d.leaf?d.state="expanded":d.state=d.leaf?"leaf":"collapsed"};a.ca.prototype.nda=function(a,d){var c={maxCount:this.xr};0<=this.Je()&&
(c.start=this.ah(this.Je()).key);this.Dd.Eu(null,{success:function(c){this.Ofa(c,a,d)}.bind(this),error:function(a){this.Yl(a,d)}.bind(this)},c)};a.ca.prototype.Am=function(){return this.Dd.Am()};a.b.g("FlattenedTreeDataSource.prototype.getSortCriteria",{Am:a.ca.prototype.Am});a.ca.prototype.Ofa=function(b,d,c){var e,f,h;d.start>this.Je()?(e=this.kJ(),f=Math.min(e,d.count),b=new a.Xe(b,this.Qy.bind(this),null,this.Pi),0<=this.Je()?(h=this.AW(),e={index:0,found:!1,count:0},this.fL(b,null,0,h,f,e),
f=e.index+1):(e={count:0},this.fL(b,null,0,null,f,e),f=0),null!=c&&null!=c.success&&(b=null!=e?0===e.count?new a.Te(null,d.start):new a.Ue(b,f):new a.Ue(b),c.success.call(null,b))):this.ZN(d,c)};a.ca.prototype.fL=function(a,d,c,e,f,h){var k,l,m,n,p;k=a.ta();l=a.R();for(m=0;m<l&&h.count!=f;m++){n=a.getMetadata(k+m);p=n.key;h.checkDepth&&e.depth===c&&(h.found=!0,h.checkDepth=!1);if(null==e||h.found)this.BA(p,c,k+m,d),h.count+=1,n.state=n.leaf?"leaf":"expanded";null==e||h.found||(p===e.key?n.leaf||this.gx(p)?
h.found=!0:h.checkDepth=!0:h.index+=1);a.Qf&&this.gx(p)&&(n=a.Qf(m),null!=n&&this.fL(n,p,c+1,e,f,h))}};a.ca.prototype.expand=function(a){this.ee(a)};a.b.g("FlattenedTreeDataSource.prototype.expand",{expand:a.ca.prototype.expand});a.ca.prototype.ee=function(b,d){var c,e,f,h;c=this.Dd.ff(b);e=this.$I(c);f=this.xr;if(this.Je()+1===f&&(h=this.Mi(b),h==f-1)){this.YN(b,new a.Te(b,0),0,d);return}0==e?this.YN(b,new a.Te(b,0),0,d):this.Dd.Nf(b,{start:0,count:e},{success:function(a){this.YN(b,a,c,d)}.bind(this),
error:function(){this.epa(b)}.bind(this)})};a.ca.prototype.collapse=function(a){var d,c,e,f,h;d=this.Mi(a)+1;c=this.ah(d-1);e=0;c=c.depth;f=this.Je();for(h=d;h<f+1;h++){var k=this.ah(h).depth;if(k>c)e+=1;else if(k==c)break}if(0!=e){this.Jt()?this.Pi.push(a):this.jka(a);f=[];for(c=0;c<e;c++)f.push({key:this.ah(d+c).key,index:d+c});this.v_(d,e);this.QE(f)}this.handleEvent("collapse",{rowKey:a})};a.b.g("FlattenedTreeDataSource.prototype.collapse",{collapse:a.ca.prototype.collapse});a.ca.prototype.gx=
function(a){return this.Jt()?this.Pi&&0<this.Pi.length?-1===this.ZV(a):!0:this.Hm&&0<this.Hm.length?-1<this.mW(a):!1};a.ca.prototype.ZV=function(a){return this.yW(this.Pi,a)};a.ca.prototype.mW=function(a){return this.yW(this.Hm,a)};a.ca.prototype.yW=function(a,d){var c,e;e=-1;for(c=0;c<a.length;c++)a[c]===d&&(e=c);return e};a.ca.prototype.jka=function(a){a=this.mW(a);-1<a&&this.Hm.splice(a,1)};a.ca.prototype.dka=function(a){a=this.ZV(a);-1<a&&this.Pi.splice(a,1)};a.ca.prototype.epa=function(a){this.handleEvent("expand",
{rowKey:a})};a.ca.prototype.YN=function(b,d,c,e){var f,h,k,l,m,n,p,r,s,q,t;d=new a.Xe(d,this.Qy.bind(this));h=f=this.Mi(b)+1;k=d.ta();l=d.R();m=this.ah(f-1);n=m.depth+1;r=[];for(s=k;s<l;s++)k=d.getMetadata(s),p=k.key,this.gx(p)&&r.push(p),this.nY(f,k,m.key,s,n),f++;this.Jt()?this.dka(b):-1===this.Hm.indexOf(b)&&this.Hm.push(b);void 0!=e&&(q=e.queue,t=e.prevNodeSetInfo);void 0!=t&&(d=new a.Qg(t.nodeSet,d,b));if(0!=r.length||void 0!==q&&0!=q.length)void 0===q&&(q=[]),0<r.length&&q.push(r),void 0===
t&&(t={},t.firstIndex=h,t.firstKey=b,t.keys=[]),t.nodeSet=d,t.keys.push(b),this.e1(q,t);else{if(void 0!=t){e=t.callbacks;if(null!=e){e.success.call(null,d);return}this.rE(t.firstIndex,t.firstKey,d)}else this.rE(h,b,d);d=this.xr;-1===c&&l===this.MN()||c>l||f==d?this.kI(f):this.Je()>=d&&this.kI(d);if(void 0!=t)for(c=0;c<t.keys.length;c++)this.handleEvent("expand",{rowKey:t.keys[c]});this.handleEvent("expand",{rowKey:b})}};a.ca.prototype.e1=function(a,d){var c,e;c=a[a.length-1];e=c.shift();0===c.length&&
a.pop();this.ee(e,{prevNodeSetInfo:d,queue:a})};a.ca.prototype.nY=function(a,d,c,e,f){d=d.key;a<=this.Je()?this.BA(d,f,e,c,a):this.BA(d,f,e,c)};a.ca.prototype.kI=function(a,d){var c;void 0==d&&(d=this.Je()+1-a);c=[];for(var e=0;e<d;e++)c.push({row:this.ah(a+e).key,index:a+e});this.v_(a,d);this.QE(c)};a.ca.prototype.fga=function(a){var d,c,e;d=a.operation;c=a.parent;c=Array.isArray(c)?c[c.length-1]:c;e=a.index;"insert"===d?this.Tfa(c,e,a.data):"delete"===d?this.Cfa(c,e):"refresh"===d&&this.nga(c)};
a.ca.prototype.Tfa=function(a,d,c){var e,f;e=this.Mi(a);f=this.ah(e).depth+1;e=e+d+1;c=c.getMetadata(c.ta());this.nY(e,c,a,d,f)};a.ca.prototype.Cfa=function(b,d){var c,e,f,h,k;c=this.Mi(b);e=this.ah(c);c+=d;f=this.ah(c);a.l.assert(f.parent===e&&f.depth===e.depth+1);e=c+1;for(h=this.Je();e<=h;){k=this.ah(e);if(k.depth!=f.depth)break;e++}this.kI(c,1)};a.ca.prototype.nga=function(a){null==a&&this.refresh()};a.ca.prototype.Jt=function(){var a=this.Dd.getCapability("fetchDescendants");return void 0!=this.Pi&&
null!=a&&"disable"!=a};a.ca.prototype.tha=function(){return"enable"===this.Dd.getCapability("batchFetch")};a.ca.prototype.refresh=function(){this.Xaa()};a.ca.prototype.Mi=function(a){var d,c,e;d=this.Je();for(c=0;c<=d;c++)if(e=this.ah(c),e.key==a)return c;return-1};a.ca.prototype.getKey=function(a){return 0>a||a>this.Je()?null:this.ah(a).key};a.ca.prototype.Hoa=function(){return{start:0,end:this.Je()+1}};a.ca.prototype.Coa=function(a){var d;d=[];a=this.Mi(a);for(a=this.tj(a);null!=a;)d.push(a),a=
this.Mi(a),a=this.tj(a);return d.reverse()};a.ca.prototype.ZN=function(a,d){null!=d&&null!=d.error&&d.error.call(null)};a.ca.prototype.rE=function(){a.l.Yb()};a.ca.prototype.QE=function(){a.l.Yb()};a.ca.prototype.Je=function(){return this.Gm.length-1};a.ca.prototype.AW=function(){return this.Gm[this.Je()]};a.ca.prototype.ah=function(a){return this.Gm[a]};a.ca.prototype.tj=function(a){a=this.Gm[a];return null!=a?a.parent:null};a.ca.prototype.BA=function(a,d,c,e,f){var h={};h.key=a;h.depth=d;h.index=
c;h.parent=e;void 0===f?this.Gm.push(h):this.Gm.splice(f,0,h)};a.ca.prototype.v_=function(a,d){this.Gm.splice(a,d)};a.ca.prototype.Xaa=function(){this.Gm.length=0};a.ca.prototype.getCapability=function(a){return this.Dd.getCapability(a)};a.b.g("FlattenedTreeDataSource.prototype.getCapability",{getCapability:a.ca.prototype.getCapability});a.ya("oj.ojRowExpander",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,expand:null,collapse:null},Sk:{root:"oj-rowexpander",icon:"oj-component-icon",
clickable:"oj-clickable-icon-nocontext",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon",toucharea:"oj-rowexpander-touch-area",indent:"oj-rowexpander-indent",iconspacer:"oj-rowexpander-icon-spacer",depth0:"oj-rowexpander-depth-0",depth1:"oj-rowexpander-depth-1",depth2:"oj-rowexpander-depth-2",depth3:"oj-rowexpander-depth-3",depth4:"oj-rowexpander-depth-4",depth5:"oj-rowexpander-depth-5",depth6:"oj-rowexpander-depth-6",
depth7:"oj-rowexpander-depth-7"},Au:{ov:7,f7:53},_ComponentCreate:function(){this._super();this.element.addClass(this.Sk.root);this.aY()},aY:function(){var a=this,d;d=this.options.context;this.O="function"===typeof d.component?d.component("instance"):d.component;this.lc=d.datasource;this.depth=d.depth;this.Th=d.state;this.Rm=d.key;this.index=d.index;this.HE=d.parentKey;this.G$();this.F$();this.dD();"expanded"===this.Th||"collapsed"===this.Th?(f(this.rP).on("touchend",function(c){c.preventDefault();
a.MI()}),f(this.rP).on("click",function(c){c.preventDefault();a.MI()}),f(this.element).on("keypress",function(c){var d=c.keyCode||c.which;if(d===f.ui.keyCode.ENTER||d===f.ui.keyCode.SPACE)a.MI(),c.preventDefault(),c.target.focus()}),this.pE=this.zX.bind(this),f(this.O.element).on("ojkeydown",this.pE),this.S3=this.Mfa.bind(this),this.R3=this.tfa.bind(this),this.lc.on("expand",this.S3,this),this.lc.on("collapse",this.R3,this)):"leaf"===this.Th&&(this.pE=this.zX.bind(this),f(this.O.element).on("ojkeydown",
this.pE),f(this.icon).attr("tabindex",-1));this.Q3=this.ifa.bind(this);f(this.O.element).on("ojbeforecurrentcell",this.Q3)},refresh:function(){this.element.empty();this.aY()},_destroy:function(){f(this.O.element).off("ojkeydown",this.pE);f(this.O.element).off("ojbeforecurrentcell",this.Q3);this.lc.off("expand",this.S3,this);this.lc.off("collapse",this.R3,this);this.element.removeClass(this.Sk.root);this.element.empty()},_setOption:function(a,d,c){this._super(a,d,c);"context"==a&&this.refresh()},G$:function(){var a,
d;d=this.depth-1;if(d<this.Au.ov)this.dH(d);else{for(a=1;a<=d/this.Au.ov;a++)this.dH(this.Au.ov);a=d%this.Au.ov;a<this.Au.ov&&this.dH(a)}},dH:function(a){a=f(document.createElement("span")).addClass(this.Sk.indent).addClass(this.Sk["depth"+a]);this.element.append(a)},F$:function(){var a=f(document.createElement("div")).addClass(this.Sk.iconspacer);this.rP=f(document.createElement("div")).addClass(this.Sk.toucharea);this.icon=f(document.createElement("a")).attr("href","#").attr("aria-labelledby",this.zW()).addClass(this.Sk.icon).addClass(this.Sk.clickable);
this.element.append(a.append(this.rP.append(this.icon)))},Vp:function(a){this.icon.addClass(this.Sk[a])},Pq:function(a){this.icon.removeClass(this.Sk[a])},dD:function(){switch(this.Th){case "leaf":this.Pq("icon");this.Pq("clickable");this.Vp("leaf");break;case "collapsed":this.Vp("expand");this.HA(!1);break;case "expanded":this.Vp("collapse");this.HA(!0);break;case "loading":this.Pq("clickable"),this.Vp("lazyload")}},sL:function(){switch(this.Th){case "leaf":this.Pq("leaf");this.Vp("icon");this.Vp("clickable");
break;case "collapsed":this.Pq("expand");break;case "expanded":this.Pq("collapse");break;case "loading":this.Pq("lazyload"),this.Vp("clickable")}},ifa:function(a,d){var c,e;null!=d.currentCell&&(c="cell"==d.currentCell.type?d.currentCell.keys.row:d.currentCell.key,null!=d.previousValue&&(e="cell"==d.previousCurrentCell.type?d.previousCurrentCell.keys.row:d.previousCurrentCell.key),this.Rm===c&&e!=c&&this.O.$C&&(c=this.A("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.lc.getWrappedDataSource().ff(this.HE)}),
e="collapsed"===this.Th?this.A("accessibleStateCollapsed"):"expanded"===this.Th?this.A("accessibleStateExpanded"):"",this.O.$C({context:c,state:e})))},zX:function(b,d){var c,e,g;if(this.Rm===d.rowKey&&(b=b.originalEvent,c=b.keyCode||b.which,a.v.Fm(b)))if(c==f.ui.keyCode.RIGHT&&"collapsed"===this.Th)this.HK(),this.lc.expand(this.Rm),b.preventDefault();else if(c==f.ui.keyCode.LEFT&&"expanded"===this.Th)this.HK(),this.lc.collapse(this.Rm),b.preventDefault();else if(b.altKey&&c==this.Au.f7&&this.O.$C){c=
this.lc.Coa(this.Rm);if(null!=c&&0<c.length)for(e=[],g=0;g<c.length;g++)e.push({key:c[g],label:this.A("accessibleLevelDescription",{level:g+1})});c=this.A("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.lc.getWrappedDataSource().ff(this.HE)});this.O.$C({context:c,state:"",ancestors:e});b.preventDefault()}},HK:function(){this.sL();this.Th="loading";this.dD()},Mfa:function(a){a=a.rowKey;a===this.Rm&&(this.sL(),this.Th="expanded",this.dD(),this.HA(!0),this._trigger("expand",
null,{rowKey:a}))},tfa:function(a){a=a.rowKey;a===this.Rm&&(this.sL(),this.Th="collapsed",this.dD(),this.HA(!1),this._trigger("collapse",null,{rowKey:a}))},MI:function(){var a=this.Th;this.HK();"collapsed"===a?this.lc.expand(this.Rm):"expanded"===a&&this.lc.collapse(this.Rm)},HA:function(a){this.icon.attr("aria-expanded",a)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-rowexpander-disclosure"!==a&&"oj-rowexpander-icon"!==a||null==this.icon?null:
this.icon.get(0)},getSubIdByNode:function(a){return a===this.icon.get(0)?{ata:"oj-rowexpander-disclosure"}:null},wn:function(){this._super();this.icon.attr("aria-labelledby",this.zW())},zW:function(){return this.element.parent().closest("[id]").attr("id")}})});