/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){a.ya("oj.ojTrain",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selected:"",optionChange:null,beforeDeselect:null,deselect:null,beforeSelect:null,select:null},cf:0,zb:null,_ComponentCreate:function(){this._super();this.G0()},G0:function(){var a=this.options,d=a.steps;this.cf=d.length;this.su=f("\x3cdiv class\x3d'oj-train-wrapper'\x3e\x3c/div\x3e");this.su.appendTo(this.element);
this.WA=f("\x3cdiv class\x3d'oj-train-connector-wrapper'\x3e\x3c/div\x3e");this.WA.appendTo(this.su);var c=this.element.attr("class");(this.$0=null!=c&&0<=c.indexOf("oj-train-stretch"))&&this.WA.css("padding","0 "+100/(2*this.cf)+"%");this.qU=f("\x3cdiv class\x3d'oj-train-connector'\x3e\x3c/div\x3e");this.qU.appendTo(this.WA);this.bf=f("\x3cul\x3e");this.bf.addClass("oj-train-step-list");this.SH=f("\x3cdiv class\x3d'oj-train-connector-fill'\x3e\x3c/div\x3e");this.SH.appendTo(this.WA);this.Nla();this.Ej=
this.At(a.selected);-1===this.Ej&&d[0]&&d[0].id&&(this.Ej=0,a.selected=d[0].id);for(a=0;a<this.cf;a++)d=f("\x3cli\x3e").addClass("oj-train-step-list-item").attr({id:this.zb[a][1]}),d.appendTo(this.bf),this.Sca(a),this.Vca(a),this.Rca(a),this.Tca(a),this.$0&&d.css("width",100/this.cf+"%");this.SH.css({width:(this.cf-1===this.Ej?100:100/(2*(this.cf-1))+this.Ej/(this.cf-1)*100)+"%"});this.bf.appendTo(this.su);this.element.addClass("oj-train")},Nla:function(){var a=this.options;this.zb=[];for(var d=0;d<
this.cf;d++){var c=a.steps[d];this.zb[d]=Array(5);this.zb[d][0]=c.label?c.label:null;this.zb[d][1]=c.id?c.id:null;this.zb[d][2]=c.disabled?!0:!1;this.zb[d][3]=c.visited?!0:!1;this.zb[d][4]=c.messageType?c.messageType:null}},Rca:function(a){var d=f("\x3cdiv/\x3e").addClass("oj-train-button"),c=f("\x3cspan/\x3e"),e=this,g="";if(this.zb[a]){var h=this.zb[a][3],k=this.zb[a][2];this.Ej===a?(d.addClass("oj-selected"),g=" current "):h&&!k?(d.addClass("oj-visited"),g=" visited "):h||k?d.addClass("oj-disabled"):
(d.addClass("oj-default"),g=" not visited ");this.zb[a][2]||this.Ej===a||(this._hoverable(d),d.on("click"+this.eventNamespace,function(a){e.vB("selected",e.options.selected,this.parentNode.parentNode.id,a);e.refresh()}));h=this.bf.children().eq(a).find(".oj-train-button-connector");1<=h.length&&h.children().remove();h.append(d);c.text(g);c.addClass("oj-helper-hidden-accessible");this.bf.children().eq(a).find("a").append(c)}},Tca:function(a){var d=f("\x3cdiv/\x3e").addClass("oj-train-icon"),c=f("\x3cspan/\x3e"),
e="",g=this;if(this.zb[a]){var h=this.zb[a][4];"confirmation"===h?(d.addClass("oj-confirmation"),e=" Confirmation "):"info"===h?(d.addClass("oj-info"),e=" Info "):"error"===h?(d.addClass("oj-error"),e=" Error "):"fatal"===h?(d.addClass("oj-error"),e=" Error "):"warning"===h&&(d.addClass("oj-warning"),e=" Warning ");var k=this.bf.children().eq(a).find(".oj-train-button");1<=k.children().length&&k.children().remove();this.zb[a][2]||this.Ej===a||(this._hoverable(d),d.on("click"+this.eventNamespace,function(a){g.vB("selected",
g.options.selected,this.parentNode.parentNode.parentNode.id,a);g.refresh()}));null!=h&&(c.text(e),c.addClass("oj-helper-hidden-accessible"),this.bf.children().eq(a).find("a").append(c),k.append(d))}},vB:function(a,d,c,e){a={option:a,fromStep:this.getStep(d),toStep:this.getStep(c),optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};!1!==this._trigger("beforeDeselect",e,a)&&!1!==this._trigger("beforeSelect",e,a)&&(d=this.At(d),-1!==d&&(this.options.steps[d].visited=!0),this._trigger("deselect",
e,a),this.option("selected",c,{_context:{originalEvent:e,Wa:!0}}),this._trigger("select",e,a))},Vca:function(a){var d=f("\x3cdiv/\x3e");d.addClass("oj-train-button-connector");this.zb[a]&&(a<=this.Ej&&d.addClass("oj-train-fill"),a=this.bf.children().eq(a).children(),d.insertBefore(a))},Sca:function(a){var d=this;if(this.zb[a]){var c=f("\x3cdiv/\x3e").addClass("oj-train-label-wrapper"),e=f("\x3ca\x3e");e.text(this.zb[a][0]);var g=this.zb[a][2];c.append(e);e.addClass("oj-train-label");a===this.Ej?e.addClass("oj-selected"):
this.zb[a][3]&&!g?e.addClass("oj-visited"):g&&e.addClass("oj-disabled");g||(e.attr("href","#"),this._hoverable(e),e.on("click keydown"+this.eventNamespace,function(a){if(a.keyCode===f.ui.keyCode.ENTER||"click"===a.type)a.preventDefault(),d.vB("selected",d.options.selected,this.parentNode.parentNode.id,a),d.refresh(),a.keyCode===f.ui.keyCode.ENTER&&d.Ik(this.parentNode.parentNode.id)}));e=this.bf.children().eq(a).children();1<=e.length&&e[0].remove();this.bf.children().eq(a).append(c)}},At:function(a){for(var d=
0;d<this.cf;d++)if(this.zb[d]&&this.zb[d][1]===a)return d;return-1},getStep:function(a){for(var d=0;d<this.cf;d++)if(this.zb[d]&&this.zb[d][1]===a)return jQuery.extend({},this.options.steps[d]);return null},nextSelectableStep:function(){for(var a=this.At(this.options.selected);a<this.cf;a++)if(a+1<this.cf&&this.zb[a+1]&&!this.zb[a+1][2])return this.zb[a+1][1];return null},previousSelectableStep:function(){for(var a=this.At(this.options.selected);0<=a;a--)if(this.zb[a-1]&&!this.zb[a-1][2])return this.zb[a-
1][1];return null},setStep:function(a){if(a.id){var d=this.getStep(a.id),c=this.At(a.id);-1!==c&&(c=this.options.steps[c],a.label&&(d[0]=a.label,c.label=a.label),"boolean"===typeof a.disabled&&(d[2]=a.disabled,c.disabled=a.disabled),"boolean"===typeof a.visited&&(d[3]=a.visited,c.visited=a.visited),a.messageType&&(d[4]=a.messageType,c.messageType=a.messageType));this.refresh()}},_setOptions:function(a){this._super(a);this.refresh()},_setOption:function(a,d,c){"selected"===a&&this.options.selected&&
this.zb&&this.zb[this.Ej]&&this.vB("selected",this.zb[this.Ej][1],d,null);this._super(a,d,c)},refresh:function(){this._super();this._destroy();this.G0()},_destroy:function(){this.bf.children().each(function(){f(this).remove()});this.element.removeClass("oj-train");this.element.find(".oj-train-wrapper").remove();this.element.find(".oj-train-connector-wrapper").remove();this.element.find(".oj-train-step-list").remove();this.element.find(".oj-train-step-list").remove();this._super()},Ik:function(a){a=
this.At(a);for(var d=0;d<this.cf;d++)if(this.zb[(a+d+1)%this.cf]&&!this.zb[(a+d+1)%this.cf][2]){this.bf.children().eq((a+d+1)%this.cf).find(".oj-train-label").focus();break}},getNodeBySubId:function(a){if(null===a)return this.element?this.element[0]:null;var d=a.index;if("number"!==typeof d||0>d||d>=this.cf)return null;switch(a.subId){case "oj-train-step":return this.bf.children().eq(d)[0];case "oj-train-button":return this.bf.children().eq(d).find(".oj-train-button")[0];case "oj-train-button-connector":return this.bf.children().eq(d).find(".oj-train-button-connector")[0];
case "oj-train-connector":return this.qU;case "oj-train-connector-fill":return this.SH;case "oj-train-icon":return this.bf.children().eq(d).find(".oj-train-icon")[0];case "oj-train-label":return this.bf.children().eq(d).find(".oj-train-label")[0]}return null},getSubIdByNode:function(a){for(var d=this.zb?this.zb.length:0,c=0;c<d;c++){var e={subId:"oj-train-step",index:c};if(a===this.getNodeBySubId(e))return e}return null}})})()});